# GDELT Data
EDA approaches to gathering energy based sources from GDELT

### Imports and Notebook Settings

In [1]:
import os 
import re
from pathlib import Path

In [2]:
import pandas as pd
import numpy as np 

import matplotlib.pyplot as plt
# import seaborn as sns 
import plotly.express as px
import pprint

In [3]:
%load_ext autoreload
%autoreload 2

In [4]:
ROOT = Path.cwd().parent

In [5]:
style_path = ( ROOT 
              / 'notebooks' 
              / 'styler.mplstyle'
              )
plt.style.use(style_path)

In [6]:
import requests

### Load Data

In [7]:
DATA_PATH = ROOT / 'data' / 'samples' / 'gkg_sample_2025-01-01_to_2025-12-31_3days_per_month_4files_per_day.parquet'

In [8]:
df = pd.read_parquet(DATA_PATH)

In [9]:
len(df)

171090

In [10]:
df.head(3)

,GKGRECORDID,DATE,SourceCollectionIdentifier,SourceCommonName,DocumentIdentifier,Counts,V2Counts,Themes,V2Themes,Locations,...,RelatedImages,SocialImageEmbeds,SocialVideoEmbeds,Quotations,AllNames,Amounts,TranslationInfo,Extras,GDELT_TIMESTAMP,GDELT_URL
0,20250101000000-0,20250101000000,1,crooksandliars.com,https://crooksandliars.com/2024/12/retired-gen...,None,None,CRISISLEX_C07_SAFETY;WB_2470_PEACE_OPERATIONS_...,"TAX_MILITARY_TITLE_LIEUTENANT,90;TAX_MILITARY_...","4#Shanghai, Shanghai, China#CH#CH23#31.2222#12...",...,None,None,https://youtube.com/embed/3q5NHISy1G0;,None,"Elon Musk,10;Lieutenant General Russel,108;Chi...",None,None,<PAGE_LINKS>https://www.independent.co.uk/news...,20250101000000,http://data.gdeltproject.org/gdeltv2/202501010...
1,20250101000000-1,20250101000000,1,weartv.com,https://weartv.com/news/nation-world/court-doc...,"ARREST#100##3#Fayette County, Alabama, United ...","ARREST#100##3#Fayette County, Alabama, United ...",AFFECT;TAX_FNCACT;TAX_FNCACT_CHILD;TAX_FNCACT_...,"TAX_FNCACT_CHILD,295;TAX_FNCACT_CHILD,1272;TAX...","2#Alabama, United States#US#USAL#32.799#-86.80...",...,None,None,https://youtube.com/c/NewsChannel8Tulsa/videos;,None,"Wendy Pamela Bailey,212;Kahleb Rowan Collins,3...","2,occasions,434;3,weeks,1585;100,dollars ,1688;",None,<PAGE_AUTHORS>CYNTHIA GOULD;WBMA staff</PAGE_A...,20250101000000,http://data.gdeltproject.org/gdeltv2/202501010...
2,20250101000000-2,20250101000000,1,yahoo.com,https://www.yahoo.com/news/fbi-says-seized-big...,None,None,TAX_FNCACT;TAX_FNCACT_MAN;ARREST;SOC_GENERALCR...,"TAX_WEAPONS_EXPLOSIVES,150;TAX_FNCACT_MAN,14;T...",None,...,None,None,https://youtube.com/yahoo;,None,"Ken Dilanian,189",None,None,<PAGE_PRECISEPUBTIMESTAMP>20241231230300</PAGE...,20250101000000,http://data.gdeltproject.org/gdeltv2/202501010...

In [11]:
df['DATETIME'] = pd.to_datetime(df['DATE'])

### General Data Structure

In [12]:
def parse_multi(value: str) -> set[str]:
    if pd.isna(value):
        return set()

    return {
        theme.strip().upper()
        for theme in value.split(";")
        if theme.strip()
    }

In [13]:
rows = len(df)
cols = len(df.iloc[0])

print(f"Dataframe has dimension of {rows} Rows and {cols} Cols")

Dataframe has dimension of 171090 Rows and 30 Cols

In [14]:
pprint.pprint(list(df.columns))

['GKGRECORDID',
 'DATE',
 'SourceCollectionIdentifier',
 'SourceCommonName',
 'DocumentIdentifier',
 'Counts',
 'V2Counts',
 'Themes',
 'V2Themes',
 'Locations',
 'V2Locations',
 'Persons',
 'V2Persons',
 'Organizations',
 'V2Organizations',
 'Tone',
 'Dates',
 'GCAM',
 'SharingImage',
 'RelatedImages',
 'SocialImageEmbeds',
 'SocialVideoEmbeds',
 'Quotations',
 'AllNames',
 'Amounts',
 'TranslationInfo',
 'Extras',
 'GDELT_TIMESTAMP',
 'GDELT_URL',
 'DATETIME']

In [15]:
print("Perecentage of Missing Values")
df.isna().sum() / len(df)

Perecentage of Missing Values

GKGRECORDID                   0.000000
DATE                          0.000000
SourceCollectionIdentifier    0.000000
SourceCommonName              0.000000
DocumentIdentifier            0.000000
Counts                        0.876357
V2Counts                      0.876357
Themes                        0.109673
V2Themes                      0.109679
Locations                     0.261009
V2Locations                   0.262090
Persons                       0.203706
V2Persons                     0.211059
Organizations                 0.260290
V2Organizations               0.289386
Tone                          0.000000
Dates                         0.635759
GCAM                          0.000000
SharingImage                  0.126267
RelatedImages                 0.875738
SocialImageEmbeds             0.882986
SocialVideoEmbeds             0.444141
Quotations                    0.774154
AllNames                      0.044731
Amounts                       0.259489
TranslationInfo               1.000000
Extras                        0.000000
GDELT_TIMESTAMP               0.000000
GDELT_URL                     0.000000
DATETIME                      0.000000
dtype: float64

In [16]:
print("First Row")

df.iloc[0]

First Row

GKGRECORDID                                                    20250101000000-0
DATE                                                             20250101000000
SourceCollectionIdentifier                                                    1
SourceCommonName                                             crooksandliars.com
DocumentIdentifier            https://crooksandliars.com/2024/12/retired-gen...
Counts                                                                     None
V2Counts                                                                   None
Themes                        CRISISLEX_C07_SAFETY;WB_2470_PEACE_OPERATIONS_...
V2Themes                      TAX_MILITARY_TITLE_LIEUTENANT,90;TAX_MILITARY_...
Locations                     4#Shanghai, Shanghai, China#CH#CH23#31.2222#12...
V2Locations                   4#Shanghai, Shanghai, China#CH#CH23#13243#31.2...
Persons                                                               elon musk
V2Persons                                            Elon Musk,9;Elon Musk,1283
Organizations                 spacex;new york times;chinese communist party;...
V2Organizations               Spacex,417;Spacex,1473;New York Times,366;New ...
Tone                          -0.387596899224806,3.87596899224806,4.26356589...
Dates                                                                      None
GCAM                          wc:234,c12.1:16,c12.10:23,c12.11:1,c12.12:4,c1...
SharingImage                  https://crooksandliars.com/files/embeds/2024/1...
RelatedImages                                                              None
SocialImageEmbeds                                                          None
SocialVideoEmbeds                        https://youtube.com/embed/3q5NHISy1G0;
Quotations                                                                 None
AllNames                      Elon Musk,10;Lieutenant General Russel,108;Chi...
Amounts                                                                    None
TranslationInfo                                                            None
Extras                        <PAGE_LINKS>https://www.independent.co.uk/news...
GDELT_TIMESTAMP                                                  20250101000000
GDELT_URL                     http://data.gdeltproject.org/gdeltv2/202501010...
DATETIME                                                    2025-01-01 00:00:00
Name: 0, dtype: object

#### Locations

In [17]:
locations = (
    df["Locations"]
    .dropna()
    .str.split(";")
    .explode()
    .reset_index()
)

locations.head()

   index                                          Locations
0      0  4#Shanghai, Shanghai, China#CH#CH23#31.2222#12...
1      0  2#New York, United States#US#USNY#42.1497#-74....
2      0                            1#China#CH#CH#35#105#CH
3      1  2#Alabama, United States#US#USAL#32.799#-86.80...
4      1  3#Fayette County, Alabama, United States#US#US...

In [18]:
location_parts = locations["Locations"].str.split("#", expand=True)

location_parts.columns = [
    "location_type",
    "location_name",
    "country_code",
    "adm1_code",
    "latitude",
    "longitude",
    "feature_id",
    "extra",
]

location_parts = pd.concat(
    [locations[["index"]], location_parts],
    axis=1
)

In [19]:
location_parts

,index,location_type,location_name,country_code,adm1_code,latitude,longitude,feature_id,extra
0,0,4,"Shanghai, Shanghai, China",CH,CH23,31.2222,121.458,-1924465,None
1,0,2,"New York, United States",US,USNY,42.1497,-74.9384,NY,None
2,0,1,China,CH,CH,35,105,CH,None
3,1,2,"Alabama, United States",US,USAL,32.799,-86.8073,AL,None
4,1,3,"Fayette County, Alabama, United States",US,USAL,33.7334,-87.7167,161554,None
...,...,...,...,...,...,...,...,...,...
493254,171086,3,"White House, District Of Columbia, United States",US,USDC,38.8951,-77.0364,531871,None
493255,171086,1,United States,US,US,39.828175,-98.5795,US,None
493256,171086,3,"National Trust For Historic Preservation, Dist...",US,USDC,38.9093,-77.0419,530124,None
493257,171086,2,"Florida, United States",US,USFL,27.8333,-81.717,FL,None
493258,171086,3,"Washington, Washington, United States",US,USDC,38.8951,-77.0364,531871,None

In [20]:
(location_parts['country_code'].value_counts() / len(location_parts)).head(5)

country_code
US    0.512623
UK    0.062774
AS    0.054428
CA    0.050943
IN    0.022400
Name: count, dtype: float64

In [21]:
location_parts["location_name"].value_counts().head(20)

location_name
United States                                       35163
Washington, Washington, United States               13409
United Kingdom                                      12925
New York, United States                             12334
Canada                                              10069
Australia                                            9761
California, United States                            8105
Texas, United States                                 7551
China                                                7375
White House, District Of Columbia, United States     7327
London, London, City Of, United Kingdom              5468
Russia                                               5440
Florida, United States                               5173
France                                               4588
Israel                                               4236
Ukraine                                              3882
Japan                                                3807
India                                                3597
Germany                                              3543
Mexico                                               3416
Name: count, dtype: int64

In [22]:
city_names = location_parts.loc[(location_parts['country_code'] == 'US') & (location_parts['location_name'] != 'United States'), 'location_name']

In [23]:
city_names.value_counts().head(20)

location_name
Washington, Washington, United States               13409
New York, United States                             12334
California, United States                            8105
Texas, United States                                 7551
White House, District Of Columbia, United States     7327
Florida, United States                               5173
Chicago, Illinois, United States                     3204
Michigan, United States                              2835
Minnesota, United States                             2780
Hollywood, California, United States                 2777
Georgia, United States                               2574
Virginia, United States                              2454
Ohio, United States                                  2342
Illinois, United States                              2329
Tennessee, United States                             2327
Los Angeles, California, United States               2303
Pennsylvania, United States                          2175
Arizona, United States                               2119
Colorado, United States                              1945
North Carolina, United States                        1941
Name: count, dtype: int64

#### URLS

In [24]:
df['SourceCommonName'].value_counts().head(10)

SourceCommonName
iheart.com         13364
yahoo.com           6351
tvguide.co.uk       2463
biztoc.com          1247
justjared.com        755
indiatimes.com       754
dailymail.co.uk      677
miragenews.com       668
amazonaws.com        472
thestar.com.my       461
Name: count, dtype: int64

#### Themes

In [25]:
Themes = (df['Themes']
          .str
          .strip()
          .str
          .split(';')
          .explode()
          .reset_index()
)

In [26]:
for i in Themes:
    print(i)

index
Themes

In [27]:
Themes.value_counts().head()

index   Themes
81111   SOC_POINTSOFINTEREST_JAIL    3
138645  TAX_FNCACT_ACTIVISTS         3
131614  SOC_POINTSOFINTEREST_JAIL    3
96997   SOC_POINTSOFINTEREST_JAIL    3
116264  SOC_POINTSOFINTEREST_JAIL    2
Name: count, dtype: int64

#### Names and Organizations

In [28]:
df.columns

Index(['GKGRECORDID', 'DATE', 'SourceCollectionIdentifier', 'SourceCommonName',
       'DocumentIdentifier', 'Counts', 'V2Counts', 'Themes', 'V2Themes',
       'Locations', 'V2Locations', 'Persons', 'V2Persons', 'Organizations',
       'V2Organizations', 'Tone', 'Dates', 'GCAM', 'SharingImage',
       'RelatedImages', 'SocialImageEmbeds', 'SocialVideoEmbeds', 'Quotations',
       'AllNames', 'Amounts', 'TranslationInfo', 'Extras', 'GDELT_TIMESTAMP',
       'GDELT_URL', 'DATETIME'],
      dtype='object')

In [29]:
def parse_organizations(value: str):
    if pd.isna(value):
        return []

    return {
        org.rsplit(",", 1)[0].strip()
        for org in value.split(";")
        if org.strip()
    }

In [30]:
orgs = (
    df["V2Organizations"]
    .dropna()
    .apply(parse_organizations)
    .explode()
)

In [31]:
orgs.value_counts().head(20)

V2Organizations
United States         12838
White House            7330
Instagram              5608
Associated Press       5471
Facebook               3596
Google                 2276
Youtube                2195
Supreme Court          2062
Cnn                    1935
Netflix                1726
New York Times         1565
Oval Office            1540
Reuters                1512
Nasdaq                 1392
Justice Department     1360
Twitter                1262
European Union         1200
Human Services         1182
United Nations         1153
Espn                   1132
Name: count, dtype: int64

In [32]:
Names = (
    df['Persons'].str.strip()
    .str.lower()
    .str.split(';')
    .explode()
)

In [33]:
Names.value_counts().head(20)

Persons
donald trump           14882
los angeles             4531
joe biden               2974
elon musk               1732
vladimir putin          1492
pete hegseth            1296
las vegas               1226
keir starmer            1214
marco rubio              939
jeffrey epstein          888
pam bondi                846
barack obama             841
robert f kennedy jr      834
karoline leavitt         811
volodymyr zelenskyy      801
kamala harris            754
taylor swift             746
benjamin netanyahu       732
gavin newsom             709
mark carney              658
Name: count, dtype: int64

### Finding Energy Specific Articles

#### Theme based Filtering

In [34]:
TARGET_THEMES = {
    "NATURAL_DISASTER",
    "FLOODING",
    "DROUGHT",
    "HURRICANE",
    "SEVERE_WEATHER",
    "WEATHER",
    "STORM",
    "WILDFIRE", 
    "ENERGY"
}


def has_target_theme(value):
    if pd.isna(value):
        return False

    themes = {
        t.strip().upper()
        for t in value.split(";")
    }

    return bool(themes & TARGET_THEMES)

In [35]:
energy_themes_df = df[
    df["Themes"].apply(has_target_theme)
]

In [36]:
print(f"Original: {len(df):,}")
print(f"Filtered: {len(energy_themes_df):,}")
print(f"Kept: {len(energy_themes_df)/len(df):.2%}")

Original: 171,090
Filtered: 14,716
Kept: 8.60%

In [37]:
sample = energy_themes_df.sample(10, random_state=42)

for i, row in sample.iterrows():
    print("=" * 100)
    print(row["DocumentIdentifier"])

    for theme in sorted(row["Themes"].split(";")):
        print(f"  {theme}")

    print()

====================================================================================================
https://www.hopestandard.com/local-news/sunshine-valley-wildfire-now-held-8225002

  CRISISLEX_CRISISLEXREC
  CRISISLEX_O01_WEATHER
  CRISISLEX_T01_CAUTION_ADVICE
  NATURAL_DISASTER
  NATURAL_DISASTER_WILDFIRE

====================================================================================================
https://www.falmouthpacket.co.uk/news/national/25429131.lammy-puts-pressure-israel-gaza-aid-access/

  AFFECT
  ARMEDCONFLICT
  CEASEFIRE
  CRISISLEX_C03_WELLBEING_HEALTH
  EPU_POLICY
  EPU_POLICY_GOVERNMENT
  EVACUATION
  FOOD_SECURITY
  GENERAL_GOVERNMENT
  GENERAL_HEALTH
  KIDNAP
  MEDICAL
  NATURAL_DISASTER
  NATURAL_DISASTER_FAMINE
  RELEASE_HOSTAGE
  TAX_AIDGROUPS
  TAX_AIDGROUPS_OXFAM
  TAX_ETHNICITY
  TAX_ETHNICITY_PALESTINIANS
  TAX_FNCACT
  TAX_FNCACT_BABIES
  TAX_FNCACT_MIDWIVES
  TAX_FNCACT_OFFICIAL
  TAX_FNCACT_SECRETARY
  TAX_FNCACT_WOMEN
  TAX_POLITICAL_PARTY
  TAX_POLITICAL_PARTY_HAMAS
  TAX_TERROR_GROUP
  TAX_TERROR_GROUP_HAMAS
  UNGP_CLEAN_WATER_SANITATION
  UNGP_FORESTS_RIVERS_OCEANS
  WATER_SECURITY
  WB_1331_HEALTH_TECHNOLOGIES
  WB_1350_PHARMACEUTICALS
  WB_1362_MEDICAL_EQUIPMENT
  WB_137_WATER
  WB_1455_MIDWIVES
  WB_1458_HEALTH_PROMOTION_AND_DISEASE_PREVENTION
  WB_1462_WATER_SANITATION_AND_HYGIENE
  WB_621_HEALTH_NUTRITION_AND_POPULATION
  WB_635_PUBLIC_HEALTH
  WB_639_REPRODUCTIVE_MATERNAL_AND_CHILD_HEALTH
  WB_641_REPRODUCTIVE_AND_MATERNAL_HEALTH

====================================================================================================
http://www.saltlakecitysun.com/news/278480989/tactical-resources-announces-execution-of-amendment-to-business-combination-agreement-with-plum-acquisition-corp-iii

  AFFECT
  CRISISLEX_C07_SAFETY
  ECON_STOCKMARKET
  ENV_MINING
  EPU_CATS_FINANCIAL_REGULATION
  EPU_CATS_NATIONAL_SECURITY
  EPU_CATS_REGULATION
  EPU_ECONOMY
  EPU_ECONOMY_HISTORIC
  EPU_POLICY
  EPU_POLICY_GOVERNMENT
  EPU_POLICY_POLITICAL
  EPU_POLICY_REFORM
  EPU_POLICY_REGULATION
  EPU_POLICY_REGULATORY
  GENERAL_GOVERNMENT
  GENERAL_HEALTH
  IDEOLOGY
  KILL
  LEGISLATION
  MANMADE_DISASTER_IMPLIED
  MEDICAL
  NATURAL_DISASTER
  NATURAL_DISASTER_NATURAL_DISASTERS
  SLFID_MINERAL_RESOURCES
  SOC_INNOVATION
  TAX_ECON_PRICE
  TAX_ETHNICITY
  TAX_ETHNICITY_CANADIAN
  TAX_FNCACT
  TAX_FNCACT_ADMINISTRATORS
  TAX_FNCACT_CHIEF
  TAX_FNCACT_CHIEF_EXECUTIVE
  TAX_FNCACT_CHIEF_EXECUTIVE_OFFICER
  TAX_FNCACT_DIRECTORS
  TAX_FNCACT_EMPLOYEE
  TAX_FNCACT_EMPLOYEES
  TAX_FNCACT_EXECUTIVE
  TAX_FNCACT_EXECUTIVE_OFFICER
  TAX_FNCACT_EXECUTIVE_OFFICERS
  TAX_FNCACT_OFFICER
  TAX_FNCACT_OFFICERS
  TAX_MILITARY_TITLE
  TAX_MILITARY_TITLE_OFFICER
  TAX_MILITARY_TITLE_OFFICERS
  UNGP_FORESTS_RIVERS_OCEANS
  USPEC_POLICY1
  USPEC_POLITICS_GENERAL1
  WB_1014_CRIMINAL_JUSTICE
  WB_1245_FINANCIAL_VULNERABILITY_AND_RISKS
  WB_1247_MARKET_RISKS
  WB_133_INFORMATION_AND_COMMUNICATION_TECHNOLOGIES
  WB_1441_SUPPLEMENTS
  WB_1920_FINANCIAL_SECTOR_DEVELOPMENT
  WB_1921_PRIVATE_SECTOR_DEVELOPMENT
  WB_2165_HEALTH_EMERGENCIES
  WB_2166_HEALTH_EMERGENCY_PREPAREDNESS_AND_DISASTER_RESPONSE
  WB_2167_PANDEMICS
  WB_2432_FRAGILITY_CONFLICT_AND_VIOLENCE
  WB_2470_PEACE_OPERATIONS_AND_CONFLICT_MANAGEMENT
  WB_2490_NATIONAL_PROTECTION_AND_SECURITY
  WB_2530_BUSINESS_ENVIRONMENT
  WB_2531_INSPECTIONS_LICENSING_AND_PERMITS
  WB_318_FINANCIAL_ARCHITECTURE_AND_BANKING
  WB_346_COMPETITIVE_INDUSTRIES
  WB_405_BUSINESS_CLIMATE
  WB_621_HEALTH_NUTRITION_AND_POPULATION
  WB_635_PUBLIC_HEALTH
  WB_644_NUTRITION
  WB_678_DIGITAL_GOVERNMENT
  WB_694_BROADCAST_AND_MEDIA
  WB_696_PUBLIC_SECTOR_MANAGEMENT
  WB_840_JUSTICE

====================================================================================================
https://www.thehindu.com/news/cities/chennai/corporation-launches-15-cr-initiative-to-repair-roads-in-various-zones/article70220784.ece

  CRISISLEX_CRISISLEXREC
  CRISISLEX_O01_WEATHER
  EPU_POLICY
  EPU_POLICY_GOVERNMENT
  GENERAL_GOVERNMENT
  NATURAL_DISASTER
  NATURAL_DISASTER_FLOOD
  NATURAL_DISASTER_MONSOON
  TAX_ECON_PRICE
  TAX_FNCACT
  TAX_FNCACT_CHAIRPERSON
  TAX_FNCACT_WORKERS
  USPEC_POLITICS_GENERAL1
  WB_137_WATER
  WB_141_WATER_RESOURCES_MANAGEMENT
  WB_154_FLOOD_PROTECTION
  WB_1654_ACTIVE_LABOR_MARKET_POLICIES
  WB_2670_JOBS
  WB_2689_JOBS_DIAGNOSTICS
  WB_2745_JOB_QUALITY_AND_LABOR_MARKET_PERFORMANCE
  WB_2748_EMPLOYMENT
  WB_697_SOCIAL_PROTECTION_AND_LABOR
  WB_855_LABOR_MARKETS
  WB_856_WAGES

====================================================================================================
https://wolfradio933.iheart.com/content/2025-11-29-winter-weather-threatens-to-create-post-thanksgiving-travel-nightmare/

  AFFECT
  CRISISLEX_C04_LOGISTICS_TRANSPORT
  CRISISLEX_T01_CAUTION_ADVICE
  DELAY
  GEN_HOLIDAY
  NATURAL_DISASTER
  NATURAL_DISASTER_SEVERE_WEATHER
  NATURAL_DISASTER_WINTER_STORM
  SOC_POINTSOFINTEREST
  SOC_POINTSOFINTEREST_AIRPORT
  SOC_POINTSOFINTEREST_AIRPORTS
  TAX_ETHNICITY
  TAX_ETHNICITY_CANADIAN
  TAX_FNCACT
  TAX_FNCACT_DRIVERS
  UNGP_CRIME_VIOLENCE
  USPEC_UNCERTAINTY1
  WB_135_TRANSPORT
  WB_1803_TRANSPORT_INFRASTRUCTURE
  WB_1804_AIRPORTS

====================================================================================================
https://wpdh.com/awesome-championship-wrestling-aftershock-poughkeepsie-ny-2025/

  DISASTER_FIRE
  NATURAL_DISASTER
  NATURAL_DISASTER_AFTERSHOCK
  TAX_ECON_PRICE
  TAX_FNCACT
  TAX_FNCACT_CHAMPIONS

====================================================================================================
https://www.cessnockadvertiser.com.au/story/8947612/luxury-meets-history-at-basels-iconic-les-trois-rois-hotel/

  CRISISLEX_CRISISLEXREC
  CRISISLEX_T03_DEAD
  KILL
  MANMADE_DISASTER_IMPLIED
  MARITIME
  MARITIME_INCIDENT
  NATURAL_DISASTER
  NATURAL_DISASTER_CHILL
  TAX_FNCACT
  TAX_FNCACT_BABY
  TAX_FNCACT_BARTENDER
  TAX_FNCACT_CHEF
  TAX_FNCACT_DUCHESS
  TAX_FNCACT_KING
  TAX_FNCACT_PRINCE
  TAX_FNCACT_QUEEN
  TAX_WORLDCRUSTACEANS
  TAX_WORLDCRUSTACEANS_LOBSTER
  WB_135_TRANSPORT
  WB_1979_NATURAL_RESOURCE_MANAGEMENT
  WB_1986_MOUNTAINS
  WB_435_AGRICULTURE_AND_FOOD_SECURITY

====================================================================================================
https://kpq.com/ncw-bracing-for-first-cold-snap-of-winter-season/

  NATURAL_DISASTER
  NATURAL_DISASTER_CHILL
  NATURAL_DISASTER_COLD_SNAP
  NATURAL_DISASTER_FRIGID
  TAX_FNCACT
  TAX_FNCACT_KING
  TAX_FNCACT_METEOROLOGIST
  TAX_WORLDLANGUAGES
  TAX_WORLDLANGUAGES_OKANOGAN
  TAX_WORLDLANGUAGES_SPOKANE

====================================================================================================
https://www.click2houston.com/news/local/2025/07/31/kerr-county-sheriff-details-response-timeline-for-deadly-july-4-floods/

  AFFECT
  CRISISLEX_C04_LOGISTICS_TRANSPORT
  CRISISLEX_C06_WATER_SANITATION
  CRISISLEX_C07_SAFETY
  CRISISLEX_CRISISLEXREC
  CRISISLEX_T01_CAUTION_ADVICE
  CRISISLEX_T03_DEAD
  CRISISLEX_T04_INFRASTRUCTURE
  CRISISLEX_T09_DISPLACEDRELOCATEDEVACUATED
  EPU_POLICY
  EPU_POLICY_LAWMAKERS
  EVACUATION
  INFRASTRUCTURE_BAD_ROADS
  LEADER
  MANMADE_DISASTER
  MANMADE_DISASTER_BUILDING_COLLAPSED
  MANMADE_DISASTER_IMPLIED
  MARITIME
  MARITIME_INCIDENT
  MEDIA_MSM
  NATURAL_DISASTER
  NATURAL_DISASTER_FLASH_FLOOD
  NATURAL_DISASTER_FLOOD
  NATURAL_DISASTER_FLOODING
  NATURAL_DISASTER_FLOODS
  NATURAL_DISASTER_FLOOD_WARNING
  TAX_FNCACT
  TAX_FNCACT_CHILDREN
  TAX_FNCACT_CORPORAL
  TAX_FNCACT_DEPUTY
  TAX_FNCACT_DISPATCHER
  TAX_FNCACT_DISPATCHERS
  TAX_FNCACT_LADY
  TAX_FNCACT_LAWMAKERS
  TAX_FNCACT_OFFICIAL
  TAX_FNCACT_OFFICIALS
  TAX_FNCACT_SERGEANT
  TAX_FNCACT_SHERIFF
  TAX_FNCACT_SPEAKER
  TAX_FNCACT_VOLUNTEER
  TAX_MILITARY_TITLE
  TAX_MILITARY_TITLE_SERGEANT
  TAX_POLITICAL_PARTY
  TAX_POLITICAL_PARTY_DEMOCRAT
  USPEC_POLITICS_GENERAL1
  WB_133_INFORMATION_AND_COMMUNICATION_TECHNOLOGIES
  WB_135_TRANSPORT
  WB_137_WATER
  WB_168_ROADS_AND_HIGHWAYS
  WB_1803_TRANSPORT_INFRASTRUCTURE
  WB_1809_HIGHWAYS
  WB_1979_NATURAL_RESOURCE_MANAGEMENT
  WB_1986_MOUNTAINS
  WB_2389_RADIO_BROADCASTING
  WB_435_AGRICULTURE_AND_FOOD_SECURITY
  WB_678_DIGITAL_GOVERNMENT
  WB_694_BROADCAST_AND_MEDIA

====================================================================================================
https://newschannel20.com/news/entertainment/glen-powells-phone-keeps-buzzing-all-thanks-to-a-top-gun-maverick-group-chat

  AFFECT
  NATURAL_DISASTER
  NATURAL_DISASTER_TWISTERS
  ORGANIZED_CRIME
  TAX_FNCACT
  TAX_FNCACT_ACTOR
  TAX_FNCACT_INSIDER
  WB_2432_FRAGILITY_CONFLICT_AND_VIOLENCE
  WB_2433_CONFLICT_AND_VIOLENCE
  WB_2445_NON_STATE_SECURITY_ACTORS
  WB_2452_GANGS

In [38]:
sample = energy_themes_df.sample(10, random_state=42)

theme_df = (
    sample[["DocumentIdentifier", "Themes"]]
    .assign(
        Themes=lambda x: x["Themes"].str.split(";")
    )
    .explode("Themes")
)

theme_df

,DocumentIdentifier,Themes
113694,https://www.hopestandard.com/local-news/sunshi...,NATURAL_DISASTER
113694,https://www.hopestandard.com/local-news/sunshi...,NATURAL_DISASTER_WILDFIRE
113694,https://www.hopestandard.com/local-news/sunshi...,CRISISLEX_T01_CAUTION_ADVICE
113694,https://www.hopestandard.com/local-news/sunshi...,CRISISLEX_CRISISLEXREC
113694,https://www.hopestandard.com/local-news/sunshi...,CRISISLEX_O01_WEATHER
...,...,...
122128,https://newschannel20.com/news/entertainment/g...,WB_2445_NON_STATE_SECURITY_ACTORS
122128,https://newschannel20.com/news/entertainment/g...,NATURAL_DISASTER
122128,https://newschannel20.com/news/entertainment/g...,NATURAL_DISASTER_TWISTERS
122128,https://newschannel20.com/news/entertainment/g...,TAX_FNCACT_INSIDER
122128,https://newschannel20.com/news/entertainment/g...,

In [39]:
sample = energy_themes_df.sample(50, random_state=42)

themes = (
    sample["Themes"]
    .str.strip()
    .str.split(";")
    .explode()
    .value_counts()
    .head()
)

print(themes.to_string())

Themes
NATURAL_DISASTER          50
                          50
TAX_FNCACT                43
CRISISLEX_CRISISLEXREC    31
EPU_POLICY                25

In [40]:
theme_df

,DocumentIdentifier,Themes
113694,https://www.hopestandard.com/local-news/sunshi...,NATURAL_DISASTER
113694,https://www.hopestandard.com/local-news/sunshi...,NATURAL_DISASTER_WILDFIRE
113694,https://www.hopestandard.com/local-news/sunshi...,CRISISLEX_T01_CAUTION_ADVICE
113694,https://www.hopestandard.com/local-news/sunshi...,CRISISLEX_CRISISLEXREC
113694,https://www.hopestandard.com/local-news/sunshi...,CRISISLEX_O01_WEATHER
...,...,...
122128,https://newschannel20.com/news/entertainment/g...,WB_2445_NON_STATE_SECURITY_ACTORS
122128,https://newschannel20.com/news/entertainment/g...,NATURAL_DISASTER
122128,https://newschannel20.com/news/entertainment/g...,NATURAL_DISASTER_TWISTERS
122128,https://newschannel20.com/news/entertainment/g...,TAX_FNCACT_INSIDER
122128,https://newschannel20.com/news/entertainment/g...,

#### Organization Based Filtering

In [41]:
def parse_organizations(value: str) -> set[str]:
    if pd.isna(value):
        return set()

    return {
        org.rsplit(",", 1)[0].strip()
        for org in value.split(";")
        if org.strip()
    }

In [42]:
org_df = (
    df[["DocumentIdentifier", "V2Organizations"]]
    .dropna(subset=["V2Organizations"])
    .assign(
        organization=lambda x: x["V2Organizations"].apply(parse_organizations)
    )
    .explode("organization")
    .drop(columns=["V2Organizations"])
    .drop_duplicates()
)

In [43]:
def inspect_org(org: str, n: int = 10):
    article_ids = (
        org_df[org_df["organization"].str.upper() == org.upper()]
        ["DocumentIdentifier"]
        .drop_duplicates()
    )

    print(f"Organization: {org}")
    print(f"Articles: {len(article_ids):,}")

    sample_ids = article_ids.sample(
        min(n, len(article_ids)),
        random_state=42
    )

    sample = df[df["DocumentIdentifier"].isin(sample_ids)]

    for _, row in sample.iterrows():
        print("=" * 100)
        print(row["DocumentIdentifier"])
        print("\nThemes:")
        for theme in sorted(str(row["Themes"]).split(";")):
            print(f"  - {theme}")

        print("\nOrganizations:")
        for organization in sorted(parse_organizations(row["V2Organizations"])):
            print(f"  - {organization}")

In [44]:
inspect_org("NOAA", 10)

Organization: NOAA
Articles: 0

In [45]:
inspect_org("National Weather Service", 10)

Organization: National Weather Service
Articles: 1,017
====================================================================================================
https://www.wvik.org/2025-01-15/la-fires-are-still-raging-but-forecasters-expect-calmer-winds-in-the-coming-days

Themes:
  -
  - AFFECT
  - CRISISLEX_C07_SAFETY
  - CRISISLEX_CRISISLEXREC
  - CRISISLEX_O01_WEATHER
  - CRISISLEX_O02_RESPONSEAGENCIESATCRISIS
  - CRISISLEX_T01_CAUTION_ADVICE
  - CRISISLEX_T02_INJURED
  - CRISISLEX_T03_DEAD
  - CRISISLEX_T11_UPDATESSYMPATHY
  - DISASTER_FIRE
  - ECON_HOUSING_PRICES
  - KILL
  - LEADER
  - MANMADE_DISASTER
  - MANMADE_DISASTER_WITHOUT_POWER
  - NATURAL_DISASTER
  - NATURAL_DISASTER_HIGH_WINDS
  - NATURAL_DISASTER_STRONG_WINDS
  - POWER_OUTAGE
  - TAX_ECON_PRICE
  - TAX_FNCACT
  - TAX_FNCACT_CHIEF
  - TAX_FNCACT_FIRE_CHIEF
  - TAX_FNCACT_MAYOR
  - TAX_FNCACT_METEOROLOGIST
  - TAX_FNCACT_OFFICIALS
  - TAX_WORLDFISH
  - TAX_WORLDFISH_BASS
  - UNGP_FORESTS_RIVERS_OCEANS

Organizations:
  - National Weather Service
====================================================================================================
https://article.wn.com/view/2025/01/15/Fire_tornadoes_pose_a_threat_in_California_A_pyrotechnics_la_q/

Themes:
  -
  - CRISISLEX_CRISISLEXREC
  - CRISISLEX_O01_WEATHER
  - CRISISLEX_T01_CAUTION_ADVICE
  - NATURAL_DISASTER
  - NATURAL_DISASTER_HIGH_WINDS
  - NATURAL_DISASTER_TORNADOES
  - NATURAL_DISASTER_WILDFIRES

Organizations:
  - National Weather Service
====================================================================================================
https://www.therepublic.com/2025/02/27/wind-advisory-in-effect-friday/

Themes:
  -
  - CRISISLEX_CRISISLEXREC
  - CRISISLEX_T01_CAUTION_ADVICE
  - MANMADE_DISASTER
  - MANMADE_DISASTER_POWER_OUTAGES
  - POWER_OUTAGE
  - SHORTAGE

Organizations:
  - National Weather Service
====================================================================================================
https://roanoke.com/news/state-regional/weather/virginia/article_16a30a46-9189-5c74-8fc5-8e45055adad3.html

Themes:
  -
  - CRISISLEX_CRISISLEXREC
  - CRISISLEX_T01_CAUTION_ADVICE
  - EPU_POLICY
  - EPU_POLICY_AUTHORITIES
  - NATURAL_DISASTER
  - NATURAL_DISASTER_WILDFIRES
  - TAX_FNCACT
  - TAX_FNCACT_AUTHORITIES

Organizations:
  - National Weather Service
====================================================================================================
https://www.wtol.com/article/news/nation-world/denali-puppy-cam-weather-litter/507-cdb37b75-e0e1-4dff-b824-bd8681a02a22

Themes:
  -
  - CRISISLEX_CRISISLEXREC
  - TAX_FNCACT
  - TAX_FNCACT_OFFICIALS
  - TAX_WORLDMAMMALS
  - TAX_WORLDMAMMALS_DOG
  - TAX_WORLDMAMMALS_DOGS
  - UNGP_FORESTS_RIVERS_OCEANS
  - WB_137_WATER
  - WB_1829_ECOSYSTEM_MANAGEMENT
  - WB_1833_PROTECTED_AREAS_SYSTEMS
  - WB_3007_NATIONAL_PARKS
  - WB_566_ENVIRONMENT_AND_NATURAL_RESOURCES

Organizations:
  - Denali National Park
  - National Park Service
  - National Weather Service
====================================================================================================
https://www.bangordailynews.com/2025/05/30/bangor/bangor-police-courts/maine-police-wont-say-criminal-investigation-death-of-comfort-dog-baxter/

Themes:
  -
  - CRISISLEX_C07_SAFETY
  - CRISISLEX_CRISISLEXREC
  - CRISISLEX_O01_WEATHER
  - CRISISLEX_T02_INJURED
  - CRISISLEX_T03_DEAD
  - EPU_POLICY
  - EPU_POLICY_LAW
  - GENERAL_HEALTH
  - KILL
  - LEGISLATION
  - MANMADE_DISASTER_IMPLIED
  - MARITIME
  - MARITIME_INCIDENT
  - MEDIA_SOCIAL
  - MEDICAL
  - NATURAL_DISASTER
  - NATURAL_DISASTER_EXTREME_COLD
  - SECURITY_SERVICES
  - TAX_FNCACT
  - TAX_FNCACT_ATTORNEY
  - TAX_FNCACT_CRIMINAL
  - TAX_FNCACT_DIRECTOR
  - TAX_FNCACT_DISPATCHERS
  - TAX_FNCACT_DISTRICT_ATTORNEY
  - TAX_FNCACT_MAN
  - TAX_FNCACT_POLICE
  - TAX_FNCACT_SPOKESPERSON
  - TAX_WORLDMAMMALS
  - TAX_WORLDMAMMALS_DOG
  - TAX_WORLDMAMMALS_DOGS
  - TRIAL
  - UNGP_CRIME_VIOLENCE
  - WB_1014_CRIMINAL_JUSTICE
  - WB_1921_PRIVATE_SECTOR_DEVELOPMENT
  - WB_2024_ANTI_CORRUPTION_AUTHORITIES
  - WB_2025_INVESTIGATION
  - WB_2530_BUSINESS_ENVIRONMENT
  - WB_2531_INSPECTIONS_LICENSING_AND_PERMITS
  - WB_405_BUSINESS_CLIMATE
  - WB_696_PUBLIC_SECTOR_MANAGEMENT
  - WB_831_GOVERNANCE
  - WB_832_ANTI_CORRUPTION
  - WB_840_JUSTICE

Organizations:
  - Bangor Regional Communications Center
  - Facebook
  - Maine Bureau Of Emergency Communications
  - Maine Department Of Public Safety
  - Maine Department Of Public Safety Communications
  - Maine State Police
  - National Weather Service
====================================================================================================
https://www.butlereagle.com/20250731/heavy-rain-pummels-the-east-coast-and-sparks-localized-flash-flooding/

Themes:
  -
  - MANMADE_DISASTER
  - MANMADE_DISASTER_IMPLIED
  - MANMADE_DISASTER_WITHOUT_POWER
  - NATURAL_DISASTER
  - NATURAL_DISASTER_FLOODING
  - POWER_OUTAGE

Organizations:
  - Amtrak
  - Associated Press
  - National Weather Service
====================================================================================================
https://kxic.iheart.com/content/2025-11-29-winter-weather-threatens-to-create-post-thanksgiving-travel-nightmare/

Themes:
  -
  - AFFECT
  - CRISISLEX_C04_LOGISTICS_TRANSPORT
  - CRISISLEX_T01_CAUTION_ADVICE
  - DELAY
  - GEN_HOLIDAY
  - NATURAL_DISASTER
  - NATURAL_DISASTER_SEVERE_WEATHER
  - NATURAL_DISASTER_WINTER_STORM
  - SOC_POINTSOFINTEREST
  - SOC_POINTSOFINTEREST_AIRPORT
  - SOC_POINTSOFINTEREST_AIRPORTS
  - TAX_ETHNICITY
  - TAX_ETHNICITY_CANADIAN
  - TAX_FNCACT
  - TAX_FNCACT_DRIVERS
  - UNGP_CRIME_VIOLENCE
  - USPEC_UNCERTAINTY1
  - WB_135_TRANSPORT
  - WB_1803_TRANSPORT_INFRASTRUCTURE
  - WB_1804_AIRPORTS

Organizations:
  - National Weather Service
  - United States
====================================================================================================
https://aggie96.iheart.com/content/2025-11-29-winter-weather-threatens-to-create-post-thanksgiving-travel-nightmare/

Themes:
  -
  - AFFECT
  - CRISISLEX_C04_LOGISTICS_TRANSPORT
  - CRISISLEX_T01_CAUTION_ADVICE
  - DELAY
  - GEN_HOLIDAY
  - NATURAL_DISASTER
  - NATURAL_DISASTER_SEVERE_WEATHER
  - NATURAL_DISASTER_WINTER_STORM
  - SOC_POINTSOFINTEREST
  - SOC_POINTSOFINTEREST_AIRPORT
  - SOC_POINTSOFINTEREST_AIRPORTS
  - TAX_ETHNICITY
  - TAX_ETHNICITY_CANADIAN
  - TAX_FNCACT
  - TAX_FNCACT_DRIVERS
  - UNGP_CRIME_VIOLENCE
  - USPEC_UNCERTAINTY1
  - WB_135_TRANSPORT
  - WB_1803_TRANSPORT_INFRASTRUCTURE
  - WB_1804_AIRPORTS

Organizations:
  - National Weather Service
  - United States
====================================================================================================
https://xl93.iheart.com/content/2025-11-29-winter-weather-threatens-to-create-post-thanksgiving-travel-nightmare/

Themes:
  -
  - AFFECT
  - CRISISLEX_C04_LOGISTICS_TRANSPORT
  - CRISISLEX_T01_CAUTION_ADVICE
  - DELAY
  - GEN_HOLIDAY
  - NATURAL_DISASTER
  - NATURAL_DISASTER_SEVERE_WEATHER
  - NATURAL_DISASTER_WINTER_STORM
  - SOC_POINTSOFINTEREST
  - SOC_POINTSOFINTEREST_AIRPORT
  - SOC_POINTSOFINTEREST_AIRPORTS
  - TAX_ETHNICITY
  - TAX_ETHNICITY_CANADIAN
  - TAX_FNCACT
  - TAX_FNCACT_DRIVERS
  - UNGP_CRIME_VIOLENCE
  - USPEC_UNCERTAINTY1
  - WB_135_TRANSPORT
  - WB_1803_TRANSPORT_INFRASTRUCTURE
  - WB_1804_AIRPORTS

Organizations:
  - National Weather Service
  - United States

In [46]:
inspect_org("FEMA", 10)

Organization: FEMA
Articles: 0

Grid Operators

In [47]:
inspect_org("Midcontinent Independent System Operator", 10)

Organization: Midcontinent Independent System Operator
Articles: 0

In [48]:
inspect_org("MISO", 10)

Organization: MISO
Articles: 0

In [49]:
GRID_ORG_KEYWORDS = [
    "ERCOT",
    "ELECTRIC RELIABILITY COUNCIL OF TEXAS",
    "PJM",
    "PJM INTERCONNECTION",
    "MIDCONTINENT INDEPENDENT SYSTEM OPERATOR",
    "MISO",
    "CALIFORNIA INDEPENDENT SYSTEM OPERATOR",
    "CAISO",
    "NEW YORK INDEPENDENT SYSTEM OPERATOR",
    "NYISO",
    "ISO NEW ENGLAND",
    "NERC",
    "FERC",
    "WECC",
]

UTILITY_KEYWORDS = [
    "ENERGY",
    "ELECTRIC",
    "POWER",
    "UTILITY",
    "GRID",
]

pattern = "|".join(re.escape(x) for x in GRID_ORG_KEYWORDS + UTILITY_KEYWORDS)

grid_related_orgs = org_df[
    org_df["organization"]
    .str.upper()
    .str.contains(pattern, regex=True, na=False)
]

In [50]:

grid_related_orgs

,DocumentIdentifier,organization
12,https://www.newsday.co.zw/local-news/article/2...,National Electricity Transmission Grid South A...
12,https://www.newsday.co.zw/local-news/article/2...,Africa Electricity Supply Commission Eskom
151,https://www.brecorder.com/news/40340531/nepra-...,Energy Task
151,https://www.brecorder.com/news/40340531/nepra-...,Power Division
151,https://www.brecorder.com/news/40340531/nepra-...,National Electric Power Regulatory Authority N...
...,...,...
170892,https://www.dailymail.co.uk/money/comment/arti...,Octopus Energy
170939,https://www.thestar.com.my/business/business-n...,Cypark Renewable Energy Sdn Bhd
170947,https://island.lk/a-long-lost-son-is-found/,National People Power
171026,https://markets.financialcontent.com/stocks/ar...,Energy Era
171038,https://markets.financialcontent.com/stocks/ar...,Nextpower Inc

In [51]:
grid_org_counts = (
    grid_related_orgs["organization"]
    .value_counts()
    .reset_index()
)

grid_org_counts.columns = ["organization", "article_count"]

grid_org_counts.head(50)

                                         organization  article_count
0                                Department Of Energy            245
1                                   Energy Department            125
2                   Energy Information Administration            105
3                  International Atomic Energy Agency             78
4             International Emergency Economic Powers             52
5                                     Energy Security             51
6                               Energy United Kingdom             51
7                         International Energy Agency             44
8                  Energy Consumers Miatta Fahnbulleh             44
9                                       National Grid             43
10                             National Energy Action             43
11                       Energy Regulatory Commission             37
12                              Community Empowerment             35
13        International Emergency Economic Powers Act             33
14                                 Energy Pa Graphics             32
15                                      Senate Energy             31
16                                     Liberty Energy             30
17           National Electric Vehicle Infrastructure             30
18                                        Duke Energy             29
19                      Income Home Energy Assistance             28
20                               Great British Energy             28
21                  Australian Energy Market Operator             27
22                                    Trim Horsepower             27
23                            National Energy Council             26
24                                   Renewable Energy             26
25                                Energy Profits Levy             26
26                                 Ministry Of Energy             24
27                          Celsius Astro Vibe Energy             24
28                                Pennsylvania Energy             23
29                             Community Power Agency             23
30               A First Nations Clean Energy Network             22
31                 Australian Renewable Energy Agency             22
32                                       House Energy             22
33                                Energy Chris Wright             21
34                  National Energy Dominance Council             21
35                                       Devon Energy             20
36                      Southern Electricity Networks             20
37              International Renewable Energy Agency             18
38                                    American Energy             18
39                                          Tc Energy             18
40                         Landpower Vegetable Centre             17
41                                 People Power Party             17
42                                    Big Diva Energy             16
43                                   Endeavour Energy             16
44  Griffith University Centre For Applied Energy ...             15
45                                Mitsubishi Electric             15
46                                       Trump Energy             15
47                  Tennessee Electric Vehicle Center             15
48                                        Luma Energy             14
49                                 Centerpoint Energy             14

In [52]:
grid_article_ids = grid_related_orgs["DocumentIdentifier"].unique()

grid_articles_df = df[
    df["DocumentIdentifier"].isin(grid_article_ids)
]

In [53]:
for _, row in grid_articles_df.sample(10, random_state=42).iterrows():
    print("=" * 100)
    print(row["DocumentIdentifier"])

    print("\nThemes:")
    for theme in sorted(str(row["Themes"]).split(";")):
        print(f"  - {theme}")

    print("\nOrganizations:")
    for org in sorted(parse_organizations(row["V2Organizations"])):
        print(f"  - {org}")

====================================================================================================
https://www.wellingtontimes.com.au/story/9102196/no-silver-bullet-but-clean-energy-co-ownership-has-legs/

Themes:
  -
  - AFFECT
  - AGRICULTURE
  - ENV_WINDPOWER
  - EPU_ECONOMY_HISTORIC
  - EPU_POLICY
  - EPU_POLICY_POLICY
  - MANMADE_DISASTER_IMPLIED
  - MARITIME
  - MARITIME_INCIDENT
  - SCIENCE
  - SOC_INNOVATION
  - TAX_ETHNICITY
  - TAX_ETHNICITY_AUSTRALIAN
  - TAX_FNCACT
  - TAX_FNCACT_CHIEF
  - TAX_FNCACT_CHIEF_EXECUTIVE
  - TAX_FNCACT_CHIEF_EXECUTIVE_OFFICER
  - TAX_FNCACT_COORDINATOR
  - TAX_FNCACT_DIRECTORS
  - TAX_FNCACT_EXECUTIVE
  - TAX_FNCACT_EXECUTIVE_OFFICER
  - TAX_FNCACT_MAN
  - TAX_FNCACT_OFFICER
  - TAX_MILITARY_TITLE
  - TAX_MILITARY_TITLE_OFFICER
  - TAX_WORLDLANGUAGES
  - TAX_WORLDLANGUAGES_WIRADJURI
  - TAX_WORLDMAMMALS
  - TAX_WORLDMAMMALS_CATS
  - UNGP_FORESTS_RIVERS_OCEANS
  - USPEC_POLICY1
  - WB_1377_ECOSYSTEM_ACCESS_AND_BENEFIT_SHARING
  - WB_1458_HEALTH_PROMOTION_AND_DISEASE_PREVENTION
  - WB_1462_WATER_SANITATION_AND_HYGIENE
  - WB_1699_METAL_ORE_MINING
  - WB_2048_COMPENSATION_CAREERS_AND_INCENTIVES
  - WB_2937_SILVER
  - WB_507_ENERGY_AND_EXTRACTIVES
  - WB_566_ENVIRONMENT_AND_NATURAL_RESOURCES
  - WB_588_CONSERVATION_FINANCE
  - WB_590_ECOSYSTEMS
  - WB_621_HEALTH_NUTRITION_AND_POPULATION
  - WB_635_PUBLIC_HEALTH
  - WB_696_PUBLIC_SECTOR_MANAGEMENT
  - WB_723_PUBLIC_ADMINISTRATION
  - WB_724_HUMAN_RESOURCES_FOR_PUBLIC_SECTOR
  - WB_895_MINING_SYSTEMS

Organizations:
  - A First Nations Clean Energy Network
  - Community Power Agency
  - Stride Renewables
====================================================================================================
https://www.yahoo.com/news/warning-meters-300-000-homes-230638686.html

Themes:
  -
  - AFFECT
  - ALLIANCE
  - EPU_ECONOMY
  - EPU_ECONOMY_HISTORIC
  - EPU_POLICY
  - EPU_POLICY_GOVERNMENT
  - GENERAL_GOVERNMENT
  - MEDIA_MSM
  - POVERTY
  - RURAL
  - TAX_FNCACT
  - TAX_FNCACT_CAMPAIGNERS
  - TAX_FNCACT_DEPUTY
  - TAX_FNCACT_DIRECTOR
  - TAX_FNCACT_ENGINEER
  - TAX_FNCACT_REGULATOR
  - TAX_WORLDMAMMALS
  - TAX_WORLDMAMMALS_BEAR
  - UNGP_CRIME_VIOLENCE
  - USPEC_POLICY1
  - WB_1174_WAREHOUSING_AND_STORAGE
  - WB_133_INFORMATION_AND_COMMUNICATION_TECHNOLOGIES
  - WB_135_TRANSPORT
  - WB_137_WATER
  - WB_2943_SWITCHES
  - WB_667_ICT_INFRASTRUCTURE
  - WB_672_NETWORK_MANAGEMENT
  - WB_678_DIGITAL_GOVERNMENT
  - WB_695_POVERTY
  - WB_793_TRANSPORT_AND_LOGISTICS_SERVICES

Organizations:
  - End Fuel Poverty Coalition
  - Energy United Kingdom
====================================================================================================
http://www.lankaenews.com/news/4508/en

Themes:
  - None

Organizations:
  - Central Bank
  - Enter The National People Power
  - Revenue Department
====================================================================================================
https://www.kvpr.org/npr-news/2025-10-30/the-federal-government-is-still-shut-down-heres-what-that-means-across-the-country

Themes:
  -
  - AFFECT
  - AGRICULTURE
  - ALLIANCE
  - BORDER
  - CLOSURE
  - CRISISLEX_C04_LOGISTICS_TRANSPORT
  - CRISISLEX_C06_WATER_SANITATION
  - CRISISLEX_C07_SAFETY
  - CRISISLEX_CRISISLEXREC
  - CRISISLEX_O01_WEATHER
  - CRISISLEX_T01_CAUTION_ADVICE
  - CRISISLEX_T04_INFRASTRUCTURE
  - CRISISLEX_T05_MONEY
  - DELAY
  - DISABILITY
  - ECON_COST_OF_LIVING
  - ECON_INFLATION
  - ECON_SUBSIDIES
  - ECON_TAXATION
  - ECON_UNIONS
  - ECON_WORLDCURRENCIES
  - ECON_WORLDCURRENCIES_DOLLARS
  - EDUCATION
  - EPU_CATS_DEBT_CEILING_GOV_SHUTDOWN
  - EPU_CATS_ENTITLEMENT_PROGRAMS
  - EPU_CATS_HEALTHCARE
  - EPU_CATS_MIGRATION_FEAR_MIGRATION
  - EPU_CATS_TAXES
  - EPU_ECONOMY
  - EPU_ECONOMY_HISTORIC
  - EPU_POLICY
  - EPU_POLICY_BUDGET
  - EPU_POLICY_CONGRESS
  - EPU_POLICY_GOVERNMENT
  - EPU_POLICY_LAW
  - EPU_POLICY_LAWMAKERS
  - EPU_POLICY_POLICY
  - EPU_POLICY_SPENDING
  - EPU_POLICY_TAX
  - EPU_UNCERTAINTY
  - FOOD_SECURITY
  - GENERAL_GOVERNMENT
  - GENERAL_HEALTH
  - GOV_LOCALGOV
  - IMMIGRATION
  - LEADER
  - LEGISLATION
  - MANMADE_DISASTER_IMPLIED
  - MEDIA_MSM
  - MEDICAL
  - NATURAL_DISASTER
  - NATURAL_DISASTER_FLOOD
  - NATURAL_DISASTER_FLOODING
  - NATURAL_DISASTER_ICE
  - NATURAL_DISASTER_MONSOON
  - NATURAL_DISASTER_MONSOON_RAINS
  - NEGOTIATIONS
  - RURAL
  - SECURITY_SERVICES
  - SELF_IDENTIFIED_HUMAN_RIGHTS
  - SHORTAGE
  - SLFID_ECONOMIC_DEVELOPMENTAID
  - SOC_POINTSOFINTEREST
  - SOC_POINTSOFINTEREST_AIRPORT
  - SOC_POINTSOFINTEREST_AIRPORTS
  - SOC_POINTSOFINTEREST_SCHOOLS
  - SOC_POINTSOFINTEREST_UNIVERSITY
  - SOC_USSECURITYAGENCIES
  - TAX_ECON_PRICE
  - TAX_ETHNICITY
  - TAX_ETHNICITY_AMERICAN
  - TAX_FNCACT
  - TAX_FNCACT_AGENTS
  - TAX_FNCACT_BROKER
  - TAX_FNCACT_CEO
  - TAX_FNCACT_CHILDREN
  - TAX_FNCACT_COMMISSIONER
  - TAX_FNCACT_EMPLOYEE
  - TAX_FNCACT_EMPLOYEES
  - TAX_FNCACT_EXECUTIVES
  - TAX_FNCACT_FARMERS
  - TAX_FNCACT_FEDERAL_OFFICIALS
  - TAX_FNCACT_GUARD
  - TAX_FNCACT_IMMIGRANTS
  - TAX_FNCACT_JUDGE
  - TAX_FNCACT_LAWMAKERS
  - TAX_FNCACT_LEADER
  - TAX_FNCACT_LEADERS
  - TAX_FNCACT_MAJORITY_LEADER
  - TAX_FNCACT_MAYOR
  - TAX_FNCACT_MINORITY_LEADER
  - TAX_FNCACT_OFFICERS
  - TAX_FNCACT_OFFICIAL
  - TAX_FNCACT_OFFICIALS
  - TAX_FNCACT_PARK_RANGERS
  - TAX_FNCACT_POLITICIANS
  - TAX_FNCACT_PRESIDENT
  - TAX_FNCACT_PRINCE
  - TAX_FNCACT_SECRETARY
  - TAX_FNCACT_SENATORS
  - TAX_FNCACT_SPEAKER
  - TAX_FNCACT_SPOKESPERSON
  - TAX_FNCACT_STAFFERS
  - TAX_FNCACT_STUDENT
  - TAX_FNCACT_TOURIST
  - TAX_FNCACT_VETERAN
  - TAX_FNCACT_VETERANS
  - TAX_FNCACT_WOMEN
  - TAX_FNCACT_WORKERS
  - TAX_MILITARY_TITLE
  - TAX_MILITARY_TITLE_OFFICERS
  - TAX_POLITICAL_PARTY
  - TAX_POLITICAL_PARTY_DEMOCRAT
  - TAX_POLITICAL_PARTY_DEMOCRATS
  - TAX_POLITICAL_PARTY_REPUBLICAN
  - TAX_POLITICAL_PARTY_REPUBLICANS
  - TAX_SPECIAL_ISSUES
  - TAX_SPECIAL_ISSUES_AFFORDABLE_CARE_ACT
  - TAX_WEAPONS
  - TAX_WEAPONS_SUBMARINES
  - TAX_WORLDFISH
  - TAX_WORLDFISH_SHARK
  - TAX_WORLDLANGUAGES
  - TAX_WORLDLANGUAGES_GALLEGO
  - TAX_WORLDLANGUAGES_KANSAS
  - TAX_WORLDLANGUAGES_MASSACHUSETTS
  - TAX_WORLDLANGUAGES_OREGON
  - TAX_WORLDMAMMALS
  - TAX_WORLDMAMMALS_HUMAN
  - TOURISM
  - TRAFFIC
  - TRIAL
  - UNEMPLOYMENT
  - UNGP_CRIME_VIOLENCE
  - UNGP_FORESTS_RIVERS_OCEANS
  - UNGP_JOB_OPPORTUNITIES_EMPLOYMENT
  - UNGP_POLITICAL_FREEDOMS
  - UNGP_SUPPORT_FOR_PEOPLE_WHO_CANT_WORK
  - UNREST_BELLIGERENT
  - URBAN
  - USPEC_POLICY1
  - USPEC_POLITICS_GENERAL1
  - USPEC_UNCERTAINTY1
  - WB_1014_CRIMINAL_JUSTICE
  - WB_1045_TREASURY
  - WB_1104_MACROECONOMIC_VULNERABILITY_AND_DEBT
  - WB_1256_CREDIT_UNIONS
  - WB_1287_HEALTH_INSURANCE
  - WB_1291_PUBLIC_HEALTH_INSURANCE
  - WB_133_INFORMATION_AND_COMMUNICATION_TECHNOLOGIES
  - WB_135_TRANSPORT
  - WB_1458_HEALTH_PROMOTION_AND_DISEASE_PREVENTION
  - WB_1464_HEALTH_OF_THE_DISABLED
  - WB_1466_SOCIAL_ASSISTANCE
  - WB_1467_EDUCATION_FOR_ALL
  - WB_1484_EDUCATION_SKILLS_DEVELOPMENT_AND_LABOR_MARKET
  - WB_1609_FOOD_AND_IN_KIND_TRANSFERS
  - WB_1613_FOOD_STAMPS
  - WB_1618_FOOD_DISTRIBUTION
  - WB_1649_UNEMPLOYMENT_BENEFITS
  - WB_167_PORTS
  - WB_1705_DISASTER_PREPAREDNESS
  - WB_1707_CONTINGENCY_PLANNING
  - WB_1803_TRANSPORT_INFRASTRUCTURE
  - WB_1804_AIRPORTS
  - WB_1810_TRAFFIC_CONTROL_AND_MONITORING
  - WB_1829_ECOSYSTEM_MANAGEMENT
  - WB_1833_PROTECTED_AREAS_SYSTEMS
  - WB_1920_FINANCIAL_SECTOR_DEVELOPMENT
  - WB_1921_PRIVATE_SECTOR_DEVELOPMENT
  - WB_1948_SUBSIDIES
  - WB_1967_AGRICULTURAL_RISK_AND_SECURITY
  - WB_1973_FINANCIAL_RISK_REDUCTION
  - WB_2048_COMPENSATION_CAREERS_AND_INCENTIVES
  - WB_2082_LAW_ENFORCEMENT
  - WB_2131_EMPLOYABILITY_SKILLS_AND_JOBS
  - WB_2203_HUMAN_RIGHTS
  - WB_2432_FRAGILITY_CONFLICT_AND_VIOLENCE
  - WB_2470_PEACE_OPERATIONS_AND_CONFLICT_MANAGEMENT
  - WB_2482_RECONCILIATION
  - WB_2490_NATIONAL_PROTECTION_AND_SECURITY
  - WB_2491_BORDER_SECURITY
  - WB_2495_DETENTION_PRISON_AND_CORRECTIONS_REFORM
  - WB_2519_RESPONSES_TO_HUMAN_RIGHTS_ABUSES
  - WB_2575_TRADE_POLICY_AND_INVESTMENT_AGREEMENTS
  - WB_2670_JOBS
  - WB_2689_JOBS_DIAGNOSTICS
  - WB_2745_JOB_QUALITY_AND_LABOR_MARKET_PERFORMANCE
  - WB_2747_UNEMPLOYMENT
  - WB_2748_EMPLOYMENT
  - WB_2769_JOBS_STRATEGIES
  - WB_2836_MIGRATION_POLICIES_AND_JOBS
  - WB_2837_IMMIGRATION
  - WB_3007_NATIONAL_PARKS
  - WB_328_FINANCIAL_INTEGRITY
  - WB_337_INSURANCE
  - WB_363_FINANCIAL_INCLUSION
  - WB_376_INNOVATION_TECHNOLOGY_AND_ENTREPRENEURSHIP
  - WB_377_FIRM_INNOVATION_PRODUCTIVITY_AND_GROWTH
  - WB_380_FUNDING_INNOVATION
  - WB_382_TAX_CREDITS_AND_DIRECT_SUBSIDIES
  - WB_435_AGRICULTURE_AND_FOOD_SECURITY
  - WB_442_INFLATION
  - WB_470_EDUCATION
  - WB_566_ENVIRONMENT_AND_NATURAL_RESOURCES
  - WB_621_HEALTH_NUTRITION_AND_POPULATION
  - WB_625_HEALTH_ECONOMICS_AND_FINANCE
  - WB_635_PUBLIC_HEALTH
  - WB_644_NUTRITION
  - WB_678_DIGITAL_GOVERNMENT
  - WB_693_POSTAL_SERVICES
  - WB_694_BROADCAST_AND_MEDIA
  - WB_695_POVERTY
  - WB_696_PUBLIC_SECTOR_MANAGEMENT
  - WB_697_SOCIAL_PROTECTION_AND_LABOR
  - WB_698_TRADE
  - WB_699_URBAN_DEVELOPMENT
  - WB_706_EVIDENCE_BASED_POLICY
  - WB_713_PUBLIC_FINANCE
  - WB_723_PUBLIC_ADMINISTRATION
  - WB_724_HUMAN_RESOURCES_FOR_PUBLIC_SECTOR
  - WB_751_SOCIAL_INSURANCE
  - WB_752_CONTRIBUTORY_BENEFITS
  - WB_775_TRADE_POLICY_AND_INTEGRATION
  - WB_776_TRADE_POLICY
  - WB_820_DISASTER_RISK_MANAGEMENT
  - WB_831_GOVERNANCE
  - WB_838_PUBLIC_ACCOUNTABILITY_MECHANISMS
  - WB_840_JUSTICE
  - WMD

Organizations:
  - A United States Postal Service
  - Acadia National Park
  - Agriculture Department
  - America Regional Council
  - Bipartisan Policy Center
  - Boston Logan International Airport
  - Capital Area Food Bank
  - Center On Budget
  - Department Of Education
  - Department Of Homeland Security
  - Department Of Labor Industry
  - Department Of Veterans Affairs
  - Employment Security Department
  - Energy Department
  - Gleaners Food Bank
  - Human Services Jenney Samuelson
  - Income Home Energy Assistance
  - Labor Department
  - Muir Woods National Monument In Marin
  - Nashville International Airport
  - National Flood Insurance Program
  - National Head Start Association
  - National Nuclear Security Administration
  - National Park
  - National Park Service
  - National Parks
  - National Zoo
  - Office For Civil Rights
  - Office Of Detention Oversight
  - Oklahoma City National Memorial
  - Smithsonian
  - Supplemental Nutrition Assistance Program
  - Supplemental Nutrition Program For Women
  - Transportation Department
  - Transportation Security Administration
  - Treasury Department
  - University Of Hawai
  - Vermont Legislature
====================================================================================================
https://947bobfm.iheart.com/content/2025-07-31-radioactive-wasp-nest-found-at-nuclear-waste-storage-site/?pname=www.947bobfm.com&sc=dnsredirect

Themes:
  -
  - GENERAL_HEALTH
  - MANMADE_DISASTER
  - MANMADE_DISASTER_RADIOACTIVE
  - TAX_FNCACT
  - TAX_FNCACT_DIRECTOR
  - TAX_FNCACT_EXECUTIVE
  - TAX_FNCACT_EXECUTIVE_DIRECTOR
  - TAX_FNCACT_OFFICIALS
  - TAX_FNCACT_WORKERS
  - TAX_WORLDINSECTS
  - TAX_WORLDINSECTS_WASP
  - TAX_WORLDINSECTS_WASPS
  - UNGP_FORESTS_RIVERS_OCEANS
  - WMD

Organizations:
  - Cnn
  - Department Of Energy
====================================================================================================
http://www.californiatelegraph.com/news/278478732/tortoise-capital-releases-combined-2025-closed-end-fund-semi-annual-report

Themes:
  -
  - ECON_STOCKMARKET
  - EPU_POLICY
  - EPU_POLICY_LAW
  - LEGISLATION
  - TAX_FNCACT
  - TAX_FNCACT_ADVISER
  - TAX_FNCACT_FUND_MANAGER
  - TAX_FNCACT_INVESTOR
  - TAX_FNCACT_MANAGER
  - TAX_WORLDREPTILES
  - TAX_WORLDREPTILES_TORTOISE
  - UNGP_FORESTS_RIVERS_OCEANS
  - WB_133_INFORMATION_AND_COMMUNICATION_TECHNOLOGIES
  - WB_135_TRANSPORT
  - WB_678_DIGITAL_GOVERNMENT
  - WB_694_BROADCAST_AND_MEDIA
  - WB_698_TRADE

Organizations:
  - Exchange Commission
  - Impact Term Fund
  - Securities Exchange
  - Tortoise Energy Infrastructure Corp
====================================================================================================
https://www.easternriverinachronicle.com.au/story/9102192/retailers-ponder-quitting-ciggies-as-illegal-sales-soar/

Themes:
  -
  - BLACK_MARKET
  - CLOSURE
  - CRISISLEX_C07_SAFETY
  - CRISISLEX_CRISISLEXREC
  - ECON_STOCKMARKET
  - EPU_CATS_MIGRATION_FEAR_FEAR
  - EPU_CATS_TAXES
  - EPU_ECONOMY_HISTORIC
  - EPU_POLICY
  - EPU_POLICY_GOVERNMENT
  - EPU_POLICY_LAW
  - GENERAL_GOVERNMENT
  - GENERAL_HEALTH
  - KILL
  - LEGISLATION
  - MEDICAL
  - SECURITY_SERVICES
  - SOC_GENERALCRIME
  - TAX_ETHNICITY
  - TAX_ETHNICITY_AUSTRALIANS
  - TAX_ETHNICITY_BLACK
  - TAX_FNCACT
  - TAX_FNCACT_CHIEF
  - TAX_FNCACT_CHIEF_EXECUTIVE
  - TAX_FNCACT_CONSULTANT
  - TAX_FNCACT_EXECUTIVE
  - TAX_FNCACT_LANDLORDS
  - TAX_FNCACT_MAN
  - TAX_FNCACT_POLICE
  - TAX_FNCACT_VETERAN
  - TAX_WORLDLANGUAGES
  - TAX_WORLDLANGUAGES_COCH
  - TRIAL
  - USPEC_POLICY1
  - WB_1014_CRIMINAL_JUSTICE
  - WB_1920_FINANCIAL_SECTOR_DEVELOPMENT
  - WB_2082_LAW_ENFORCEMENT
  - WB_328_FINANCIAL_INTEGRITY
  - WB_621_HEALTH_NUTRITION_AND_POPULATION
  - WB_635_PUBLIC_HEALTH
  - WB_696_PUBLIC_SECTOR_MANAGEMENT
  - WB_698_TRADE
  - WB_840_JUSTICE

Organizations:
  - Viva Energy
====================================================================================================
https://www.bbc.co.uk/news/articles/c1m5rpmxy9xo

Themes:
  -
  - CLOSURE
  - CRISISLEX_T01_CAUTION_ADVICE
  - DISASTER_FIRE
  - EPU_CATS_MIGRATION_FEAR_FEAR
  - TAX_FNCACT
  - TAX_FNCACT_SPOKESMAN
  - TAX_FNCACT_SPOKESPERSON
  - WB_507_ENERGY_AND_EXTRACTIVES
  - WB_508_POWER_SYSTEMS
  - WB_509_NUCLEAR_ENERGY

Organizations:
  - National Grid
====================================================================================================
https://www.nigerianeye.com/2025/09/the-clout-chasing-is-insane-eniola.html

Themes:
  -
  - CRISISLEX_T11_UPDATESSYMPATHY
  - MEDIA_SOCIAL
  - SCIENCE
  - SOC_INNOVATION
  - TAX_FNCACT
  - TAX_FNCACT_ACTRESS
  - TAX_FNCACT_LEADERS
  - UNGP_FORESTS_RIVERS_OCEANS
  - WB_615_GENDER

Organizations:
  - Africa Center
  - Africa Forum
  - Instagram
  - Nigerian Embassy
  - Partnership For Sustainable Energy
  - United Nations
====================================================================================================
https://www.tricitynews.com/national-business/premiers-urge-unity-in-face-of-us-tariff-threats-alberta-demands-energy-exemption-10077735

Themes:
  -
  - AFFECT
  - BAN
  - BORDER
  - CRISISLEX_CRISISLEXREC
  - DRUG_TRADE
  - ENV_OIL
  - EPU_CATS_MIGRATION_FEAR_MIGRATION
  - EPU_POLICY
  - EPU_POLICY_DEFICIT
  - EPU_POLICY_GOVERNMENT
  - GENERAL_GOVERNMENT
  - IMMIGRATION
  - LEADER
  - MEDIA_MSM
  - MEDIA_SOCIAL
  - SLFID_NATURAL_RESOURCES
  - TAX_ETHNICITY
  - TAX_ETHNICITY_AMERICAN
  - TAX_ETHNICITY_AMERICANS
  - TAX_ETHNICITY_CANADIAN
  - TAX_ETHNICITY_CANADIANS
  - TAX_FNCACT
  - TAX_FNCACT_CRITIC
  - TAX_FNCACT_MINISTER
  - TAX_FNCACT_MINISTERS
  - TAX_FNCACT_OFFICIALS
  - TAX_FNCACT_PRESIDENT
  - TAX_FNCACT_PRIME_MINISTER
  - UNGP_FORESTS_RIVERS_OCEANS
  - USPEC_POLICY1
  - USPEC_POLITICS_GENERAL1
  - WB_1078_DETERMINANTS_OF_GROWTH
  - WB_1079_COMMODITIES_AND_RESOURCES
  - WB_1331_HEALTH_TECHNOLOGIES
  - WB_133_INFORMATION_AND_COMMUNICATION_TECHNOLOGIES
  - WB_1350_PHARMACEUTICALS
  - WB_2432_FRAGILITY_CONFLICT_AND_VIOLENCE
  - WB_2433_CONFLICT_AND_VIOLENCE
  - WB_2453_ORGANIZED_CRIME
  - WB_2456_DRUGS_AND_NARCOTICS
  - WB_2670_JOBS
  - WB_2769_JOBS_STRATEGIES
  - WB_2836_MIGRATION_POLICIES_AND_JOBS
  - WB_2837_IMMIGRATION
  - WB_471_ECONOMIC_GROWTH
  - WB_621_HEALTH_NUTRITION_AND_POPULATION
  - WB_652_ICT_APPLICATIONS
  - WB_658_ENTERPRISE_APPLICATIONS
  - WB_662_SOCIAL_MEDIA
  - WB_678_DIGITAL_GOVERNMENT
  - WB_694_BROADCAST_AND_MEDIA
  - WB_698_TRADE

Organizations:
  - Council Of The Federation
  - Energy Natural Resources
  - United States

### URL Based Filtering

In [54]:
URL_KEYWORDS = {
    "storm",
    "flood",
    "flooding",
    "hurricane",
    "tornado",
    "wildfire",
    "blizzard",
    "outage",
    "blackout",
    "power-outage",
    "power_outage",
    "without-power",
    "power-grid",
    "grid-congestion",  # typo fixed
}

def is_weather_url(url: str) -> bool:
    if pd.isna(url):
        return False

    url = url.lower()

    return any(
        keyword in url
        for keyword in URL_KEYWORDS
    )

In [55]:
url_articles_df = df[
    df["DocumentIdentifier"].apply(is_weather_url)
]

In [56]:
url_articles_df

,GKGRECORDID,DATE,SourceCollectionIdentifier,SourceCommonName,DocumentIdentifier,Counts,V2Counts,Themes,V2Themes,Locations,...,SocialImageEmbeds,SocialVideoEmbeds,Quotations,AllNames,Amounts,TranslationInfo,Extras,GDELT_TIMESTAMP,GDELT_URL,DATETIME
9,20250101000000-9,20250101000000,1,utv44.com,https://utv44.com/news/local/limited-tornado-d...,None,None,NATURAL_DISASTER;NATURAL_DISASTER_TORNADO;CRIS...,"EPU_ECONOMY_HISTORIC,1635;NATURAL_DISASTER_TOR...",None,...,None,https://youtube.com/channel/UCJc7is6F67EepYaJj...,None,"Mobile County Public Works,27;Mobile County,13...","2,tornados touched down,164;",None,<PAGE_AUTHORS>Keith Lane</PAGE_AUTHORS><PAGE_T...,20250101000000,http://data.gdeltproject.org/gdeltv2/202501010...,2025-01-01 00:00:00
282,20250101000000-282,20250101000000,1,fox10phoenix.com,https://www.fox10phoenix.com/news/puerto-rico-...,None,None,SECURITY_SERVICES;TAX_FNCACT;TAX_FNCACT_POLICE...,"TAX_FNCACT_OPERATOR,1338;TAX_AIDGROUPS_FEDERAL...","3#Palo Seco, Puerto Rico, United States#US#USP...",...,None,https://youtube.com/fox10phoenix;,None,"San Juan,106;Getty Images,248;New Year,412;Ass...","3000000,clients,247;47000000,clients,684;4,sto...",None,<PAGE_LINKS>https://www.foxnews.com/category/a...,20250101000000,http://data.gdeltproject.org/gdeltv2/202501010...,2025-01-01 00:00:00
388,20250101000000-388,20250101000000,1,wwmt.com,https://wwmt.com/news/local/top-stories-2024-m...,None,None,CRISISLEX_CRISISLEXREC;NATURAL_DISASTER;NATURA...,"TAX_FNCACT_SECRETARY_OF_STATE,1039;ENV_SOLAR,1...",1#United States#US#US#39.828175#-98.5795#US;2#...,...,None,https://youtube.com/user/wwmtnews;,None,"News Channel,289;West Michigan,450;West Michig...","3,top stories of 2024,228;100,of minimum wage ...",None,<PAGE_AUTHORS>Katie Sergent | News Channel 3</...,20250101000000,http://data.gdeltproject.org/gdeltv2/202501010...,2025-01-01 00:00:00
403,20250101000000-403,20250101000000,1,arlnow.com,https://www.arlnow.com/2024/12/31/just-in-seve...,None,None,CRISISLEX_O01_WEATHER;CRISISLEX_T01_CAUTION_AD...,"CRISISLEX_T01_CAUTION_ADVICE,102;CRISISLEX_T01...","3#King George County, Virginia, United States#...",...,https://pic.twitter.com/2NRwOW0f6h;,https://youtube.com/user/arlingtonnews/videos;,None,"Severe Thunderstorm,110;National Weather,269;N...","8,miles east of Quantico,1000;",None,<PAGE_LINKS>https://t.co/2NRwOW0f6h;https://tw...,20250101000000,http://data.gdeltproject.org/gdeltv2/202501010...,2025-01-01 00:00:00
429,20250101000000-429,20250101000000,1,castanetkamloops.net,https://www.castanetkamloops.net/news/BC/52530...,None,None,WB_569_HYDROMET_SERVICES;WB_568_CLIMATE_SERVIC...,"TAX_WORLDLANGUAGES_CHEYENNE,1062;UNGP_FORESTS_...","4#Vancouver, British Columbia, Canada#CA#CA02#...",...,None,None,"1242|43||Carson City , Oklahoma City , and Ral...","National Oceanic,32;Atmospheric Administration...",None,None,<PAGE_LINKS>https://weather.gc.ca/astro/clds_v...,20250101000000,http://data.gdeltproject.org/gdeltv2/202501010...,2025-01-01 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170791,20251231004500-737,20251231004500,1,cnbc.com,https://www.cnbc.com/2025/12/30/ro-khanna-call...,None,None,WB_2024_ANTI_CORRUPTION_AUTHORITIES;WB_696_PUB...,"CORRUPTION,100;WB_2019_ANTI_CORRUPTION_LEGISLA...","2#California, United States#US#USCA#36.17#-119...",...,None,https://youtube.com/user/cnbc/;https://youtube...,None,"Silicon Valley,244",None,None,<PAGE_AUTHORS>Garrett Downs</PAGE_AUTHORS><PAG...,20251231004500,http://data.gdeltproject.org/gdeltv2/202512310...,2025-12-31 00:45:00
170980,20251231004500-926,20251231004500,1,thewestmorlandgazette.co.uk,https://www.thewestmorlandgazette.co.uk/news/n...,"AFFECT#24##4#Dagenham, Barking And Dagenham, U...","AFFECT#24##4#Dagenham, Barking And Dagenham, U...",WATER_SECURITY;NATURAL_DISASTER;NATURAL_DISAST...,"NATURAL_DISASTER_WILDFIRES,268;NATURAL_DISASTE...","4#Ilford, Redbridge, United Kingdom#UK#UKK8#51...",...,None,None,415|65||exceptional bravery and professionalis...,"Press Association,624;United Kingdom,1092;Unit...","454,grassland,363;3,months,437;621,incidents l...",None,<PAGE_PRECISEPUBTIMESTAMP>20251231000700</PAGE...,20251231004500,http://data.gdeltproject.org/gdeltv2/202512310...,2025-12-31 00:45:00
170986,20251231004500-932,20251231004500,1,yahoo.com,https://www.yahoo.com/news/articles/wind-storm...,None,None,NATURAL_DISASTER;NATURAL_DISASTER_WIND_STORM;M...,"TAX_ETHNICITY_LENAPE,1273;TAX_WORLDLANGUAGES_L...","3#Montchanin, Delaware, United States#US#USDE#...",...,None,https://youtube.com/c/yahoonews;https://youtub...,None,"Radnor Township,273;Brookside Avenue,637;Candi...","500,block of Brookside Avenue,551;100,near Gre...",None,<PAGE_PRECISEPUBTIMESTAMP>20251231001800</PAGE...,20251231004500,http://data.gdeltproject.org/gdeltv2/202512310...,2025-12-31 00:45:00
171004,20251231004500-950,20251231004500,1,union-bulletin.com,https://www.union-bulletin.com/news/northwest/...,"AFFECT#5000000##2#Washington, United States#US...","AFFECT#5000000##2#Washington, United States#US...",NATURAL_DISASTER;NATURAL_DISASTER_FLOODS;CRISI...,"TAX_WORLDLANGUAGES_GREEN_RIVER,2186;CRISISLEX_...","3#Thurston County, Washington, United States#U...",...,None,https://youtube.com/unionbulletin;,2605|28||benefits from another source#4944|25|...,"Western Washingtonians,23;Ken Zweig,956;King C...","300,parcels through its flood,1704;2,business ...",None,<PAGE_LINKS>https://governor.wa.gov/news/2025/...,20251231004500,http://data.gdeltproject.org/gdeltv2/202512310...,2025-12-31 00:45:00
171075,20251231004500-1021,20251231004500,1,santamariatimes.com,https://santamariatimes.com/ap/national/midwes...,"KILL#3#hikers#2#California, United States#US#U...","KILL#3#hikers#2#California, United States#US#U...",NATURAL_DISASTER;NATURAL_DISASTER_FRIGID;NATUR...,"WB_678_DIGITAL_GOVERNMENT,2289;WB_678_DIGITAL_...","3#Newark, New Jersey, United States#US#USNJ#40...",...,None,None,3982|46||unusually cold for unusually long for...,"Great Lakes,361;Great Lakes,485;Big Bay Point ...","10,degrees Fahrenheit,1089;23,degrees Celsius,...",None,<PAGE_LINKS>http://Poweroutage.us;https://apne...,20251231004500,http://data.gdeltproject.org/gdeltv2/202512310...,2025-12-31 00:45:00

In [57]:
from collections import Counter

keyword_counts = Counter()

for url in df["DocumentIdentifier"].dropna():
    url = url.lower()

    for keyword in URL_KEYWORDS:
        if keyword in url:
            keyword_counts[keyword] += 1

pd.Series(keyword_counts).sort_values(ascending=False)

storm            925
flood            573
wildfire         539
hurricane        240
flooding         200
tornado          179
outage           152
blackout          76
power-outage      51
without-power     36
blizzard          13
power-grid         5
dtype: int64

In [58]:
def inspect_keyword(keyword, n=10):
    matches = df[
        df["DocumentIdentifier"]
        .str.lower()
        .str.contains(keyword, na=False)
    ]

    print(f"{keyword}: {len(matches):,} matches")

    return matches[
        ["DocumentIdentifier", "Themes"]
    ].sample(
        min(n, len(matches)),
        random_state=42
    )

In [59]:
inspect_keyword("outage")

outage: 152 matches

,DocumentIdentifier,Themes
78881,https://www.wsiu.org/2025-05-15/denver-air-tra...,TAX_FNCACT;TAX_FNCACT_PILOTS;SOC_POINTSOFINTER...
165066,https://www.nhpr.org/2025-12-15/waterbury-wate...,WB_137_WATER;CRISISLEX_C06_WATER_SANITATION;MA...
109763,https://www.clarksvilleonline.com/2025/08/15/c...,WB_137_WATER;AFFECT;ENV_NATURALGAS;WB_139_SANI...
90621,https://929zzu.com/2025/07/15/gusty-winds-lead...,SHORTAGE;MANMADE_DISASTER;MANMADE_DISASTER_POW...
139409,http://www.t-g.com/premium/newsusa/stories/how...,NATURAL_DISASTER;NATURAL_DISASTER_SEVERE_WEATH...
151971,https://krcrtv.com/news/local/butte-county-she...,TAX_FNCACT;TAX_FNCACT_SHERIFF;CRISISLEX_C07_SA...
44371,https://www.wpxi.com/news/local/outage-causes-...,PUBLIC_TRANSPORT;WB_1428_INJURY;WB_1406_DISEAS...
11284,https://www.illawarramercury.com.au/story/8867...,TAX_FNCACT;TAX_FNCACT_HUNTER;MANMADE_DISASTER;...
22662,https://www.cowichanvalleycitizen.com/news/wea...,SHORTAGE;NATURAL_DISASTER;NATURAL_DISASTER_POW...
17588,https://www.westhawaiitoday.com/2025/01/30/haw...,WB_137_WATER;WATER_SECURITY;WB_1199_WATER_SUPP...

In [60]:
inspect_keyword("hurricane")

hurricane: 240 matches

,DocumentIdentifier,Themes
58820,https://www.sun-sentinel.com/2025/04/14/hurric...,NATURAL_DISASTER;NATURAL_DISASTER_HURRICANES;C...
26457,https://b1039.com/2025/02/14/beach-closures-af...,None
120692,https://wcti12.com/news/local/hurricane-floren...,NATURAL_DISASTER;NATURAL_DISASTER_HURRICANE;CR...
125990,https://eagle1005.com/news/030030-1-man-killed...,TAX_FNCACT;TAX_FNCACT_AUTHORITIES;CRISISLEX_CR...
124104,https://www.wapt.com/article/government-shutdo...,UNREST_BELLIGERENT;GENERAL_GOVERNMENT;EPU_POLI...
142334,https://www.tenterfieldstar.com.au/story/91014...,NATURAL_DISASTER;NATURAL_DISASTER_HURRICANE;CR...
163853,https://www.orlandosentinel.com/2025/12/15/dav...,None
111656,https://www.timesleader.com/news/1713301/heavy...,NATURAL_DISASTER;NATURAL_DISASTER_HURRICANE;CR...
33303,https://www.yourobserver.com/news/2025/feb/27/...,TAX_FNCACT;TAX_FNCACT_BOARD_MEMBERS;TAX_FNCACT...
139992,http://www.jamaicantimes.com/news/278665419/hu...,NATURAL_DISASTER;NATURAL_DISASTER_HURRICANE;CR...

In [61]:
inspect_keyword("power-grid")

power-grid: 5 matches

,DocumentIdentifier,Themes
89606,https://www.renewableenergyworld.com/power-gri...,TAX_FNCACT;TAX_FNCACT_MODERATOR;WB_2745_JOB_QU...
134311,https://www.northcentralpa.com/features/spotli...,TAX_ECON_PRICE;ECON_ELECTRICALPRICE;ECON_ELECT...
101938,https://www.kgou.org/2025-07-31/how-utilities-...,ECON_ELECTRICALGRID;SHORTAGE;
85880,https://jamaica-gleaner.com/article/news/20250...,LEADER;TAX_FNCACT;TAX_FNCACT_GOVERNOR;USPEC_PO...
112029,https://www.theverge.com/news/760253/tech-ai-p...,ARMEDCONFLICT;EPU_POLICY;EPU_POLICY_POLITICAL;

### Relevence Scoring

In [62]:
TARGET_THEMES = {
    "WEATHER",
    "NATURAL_DISASTER",
    "FLOODING",
    "DROUGHT",
    "HURRICANE",
    "STORM",
    "WILDFIRE",
    "EXTREME_WEATHER",
}

WEATHER_ORG_KEYWORDS = [
    "NOAA",
    "NATIONAL WEATHER SERVICE",
    "NATIONAL HURRICANE CENTER",
    "FEMA",
    "EMERGENCY MANAGEMENT",
    "METEOROLOG",
    "DISASTER",
]

GRID_ORG_KEYWORDS = [
    "ERCOT",
    "PJM",
    "MISO",
    "CAISO",
    "NYISO",
    "ISO NEW ENGLAND",
    "NERC",
    "FERC",
    "WECC",
    "ELECTRIC",
    "POWER",
    "UTILITY",
    "GRID",
]

URL_KEYWORDS = {
    "storm", "flood", "flooding", "hurricane", "tornado",
    "wildfire", "blizzard", "outage", "blackout",
    "power-outage", "power_outage", "without-power",
    "power-grid", "grid-congestion",
}


def parse_themes(value: str) -> set[str]:
    if pd.isna(value):
        return set()

    return {
        t.strip().upper()
        for t in value.split(";")
        if t.strip()
    }


def parse_organizations(value: str) -> set[str]:
    if pd.isna(value):
        return set()

    return {
        org.rsplit(",", 1)[0].strip().upper()
        for org in value.split(";")
        if org.strip()
    }


def contains_any_keyword(text: str, keywords) -> bool:
    if pd.isna(text):
        return False

    text = str(text).upper()

    return any(keyword.upper() in text for keyword in keywords)


def has_target_theme(value: str) -> bool:
    themes = parse_themes(value)
    return bool(themes & TARGET_THEMES)


def has_weather_org(value: str) -> bool:
    orgs = parse_organizations(value)
    return any(
        contains_any_keyword(org, WEATHER_ORG_KEYWORDS)
        for org in orgs
    )


def has_grid_org(value: str) -> bool:
    orgs = parse_organizations(value)
    return any(
        contains_any_keyword(org, GRID_ORG_KEYWORDS)
        for org in orgs
    )


def has_url_keyword(url: str) -> bool:
    if pd.isna(url):
        return False

    url = str(url).lower()

    return any(keyword in url for keyword in URL_KEYWORDS)


def has_us_location(value: str) -> bool:
    if pd.isna(value):
        return False

    for loc in value.split(";"):
        parts = loc.split("#")

        if len(parts) >= 3:
            country_code = parts[2]

            if country_code == "US":
                return True

    return False


def add_relevance_scores(df: pd.DataFrame) -> pd.DataFrame:
    scored = df.copy()

    scored["theme_match"] = scored["Themes"].apply(has_target_theme)
    scored["weather_org_match"] = scored["V2Organizations"].apply(has_weather_org)
    scored["grid_org_match"] = scored["V2Organizations"].apply(has_grid_org)
    scored["url_keyword_match"] = scored["DocumentIdentifier"].apply(has_url_keyword)
    scored["us_location_match"] = scored["Locations"].apply(has_us_location)


    scored = scored.loc[scored['us_location_match']]
    
    scored["relevance_score"] = (
        5 * scored["theme_match"].astype(int)
        + 4 * scored["url_keyword_match"].astype(int)
        + 3 * scored["weather_org_match"].astype(int)
        + 10 * scored["grid_org_match"].astype(int)
    )

    return scored

In [63]:
scored_df = add_relevance_scores(df)

candidates = scored_df[
    scored_df["relevance_score"] >= 5
].sort_values("relevance_score", ascending=False)

candidates[
    [
        "DocumentIdentifier",
        "relevance_score",
        "theme_match",
        "url_keyword_match",
        "weather_org_match",
        "grid_org_match",
        "us_location_match",
        "Themes",
    ]
].head(5)

,DocumentIdentifier,relevance_score,theme_match,url_keyword_match,weather_org_match,grid_org_match,us_location_match,Themes
282,https://www.fox10phoenix.com/news/puerto-rico-...,22,True,True,True,True,True,SECURITY_SERVICES;TAX_FNCACT;TAX_FNCACT_POLICE...
9707,https://www.hometownregister.com/news/national...,22,True,True,True,True,True,NATURAL_DISASTER;NATURAL_DISASTER_WILDFIRES;CR...
157458,https://kprcradio.iheart.com/content/2025-11-2...,22,True,True,True,True,True,NATURAL_DISASTER;NATURAL_DISASTER_SEVERE_WEATH...
170616,https://www.yourdailyglobe.com/story/2025/12/3...,22,True,True,True,True,True,ECON_ELECTRICALGENERATION;SHORTAGE;NATURAL_DIS...
10515,https://www.elpasoinc.com/news/national/how-to...,22,True,True,True,True,True,NATURAL_DISASTER;NATURAL_DISASTER_WILDFIRES;CR...

In [64]:
sample = (
    candidates
    .sample(25, random_state=42)
    .sort_values("relevance_score", ascending=False)
)

for i, (_, row) in enumerate(sample.iterrows(), start=1):
    print("=" * 120)

    print(f"[{i}] Score: {row['relevance_score']}")

    print("\nURL:")
    print(row["DocumentIdentifier"])

    print("\nSignals:")
    print(f"  Theme Match      : {row['theme_match']}")
    print(f"  URL Match        : {row['url_keyword_match']}")
    print(f"  Weather Org      : {row['weather_org_match']}")
    print(f"  Grid Org         : {row['grid_org_match']}")
    print(f"  US Location      : {row['us_location_match']}")

    print("\nThemes:")

    for theme in sorted(
        str(row["Themes"]).split(";")
    ):
        print(f"  - {theme}")

    print()

========================================================================================================================
[1] Score: 15

URL:
https://www.wmra.org/2025-08-15/after-a-freeze-trump-administration-reluctantly-agrees-to-fund-ev-chargers

Signals:
  Theme Match      : True
  URL Match        : False
  Weather Org      : False
  Grid Org         : True
  US Location      : True

Themes:
  -
  - ALLIANCE
  - ARMEDCONFLICT
  - CRISISLEX_O01_WEATHER
  - CRISISLEX_T01_CAUTION_ADVICE
  - CRISISLEX_T09_DISPLACEDRELOCATEDEVACUATED
  - DELAY
  - ECON_WORLDCURRENCIES
  - ECON_WORLDCURRENCIES_DOLLAR
  - ENV_CLIMATECHANGE
  - ENV_GREEN
  - EPU_CATS_MIGRATION_FEAR_FEAR
  - EPU_CATS_REGULATION
  - EPU_POLICY
  - EPU_POLICY_CONGRESS
  - EPU_POLICY_GOVERNMENT
  - EPU_POLICY_LAW
  - EPU_POLICY_POLICY
  - EPU_POLICY_SPENDING
  - GENERAL_GOVERNMENT
  - LEADER
  - LEGISLATION
  - MANMADE_DISASTER_IMPLIED
  - NATURAL_DISASTER
  - NATURAL_DISASTER_EXTREME_WEATHER
  - RURAL
  - TAX_FNCACT
  - TAX_FNCACT_ATTORNEY
  - TAX_FNCACT_CEO
  - TAX_FNCACT_DIRECTOR
  - TAX_FNCACT_DRIVERS
  - TAX_FNCACT_EXECUTIVE
  - TAX_FNCACT_EXECUTIVE_DIRECTOR
  - TAX_FNCACT_JUDGE
  - TAX_FNCACT_OFFICIALS
  - TAX_FNCACT_PRESIDENT
  - TAX_FNCACT_SECRETARY
  - TAX_FNCACT_SPOKESMAN
  - TRIAL
  - UNGP_CLIMATE_CHANGE_ACTION
  - UNGP_FORESTS_RIVERS_OCEANS
  - UNGP_JOB_OPPORTUNITIES_WORKING_CONDITIONS
  - USPEC_POLICY1
  - USPEC_POLITICS_GENERAL1
  - USPEC_UNCERTAINTY1
  - WB_135_TRANSPORT
  - WB_1458_HEALTH_PROMOTION_AND_DISEASE_PREVENTION
  - WB_1462_WATER_SANITATION_AND_HYGIENE
  - WB_1467_EDUCATION_FOR_ALL
  - WB_1484_EDUCATION_SKILLS_DEVELOPMENT_AND_LABOR_MARKET
  - WB_167_PORTS
  - WB_168_ROADS_AND_HIGHWAYS
  - WB_1803_TRANSPORT_INFRASTRUCTURE
  - WB_1809_HIGHWAYS
  - WB_1921_PRIVATE_SECTOR_DEVELOPMENT
  - WB_2131_EMPLOYABILITY_SKILLS_AND_JOBS
  - WB_2530_BUSINESS_ENVIRONMENT
  - WB_2531_INSPECTIONS_LICENSING_AND_PERMITS
  - WB_2670_JOBS
  - WB_405_BUSINESS_CLIMATE
  - WB_470_EDUCATION
  - WB_621_HEALTH_NUTRITION_AND_POPULATION
  - WB_635_PUBLIC_HEALTH

========================================================================================================================
[2] Score: 12

URL:
https://urbanmilwaukee.com/pressrelease/ahead-of-possible-weekend-storms-milwaukee-county-executive-david-crowley-urges-community-safety-and-preparation/

Signals:
  Theme Match      : True
  URL Match        : True
  Weather Org      : True
  Grid Org         : False
  US Location      : True

Themes:
  -
  - AFFECT
  - CRISISLEX_C04_LOGISTICS_TRANSPORT
  - CRISISLEX_C06_WATER_SANITATION
  - CRISISLEX_C07_SAFETY
  - CRISISLEX_CRISISLEXREC
  - CRISISLEX_O01_WEATHER
  - CRISISLEX_T01_CAUTION_ADVICE
  - CRISISLEX_T04_INFRASTRUCTURE
  - CRISISLEX_T11_UPDATESSYMPATHY
  - EPU_POLICY
  - EPU_POLICY_GOVERNMENT
  - GENERAL_GOVERNMENT
  - MEDIA_MSM
  - MEDIA_SOCIAL
  - NATURAL_DISASTER
  - NATURAL_DISASTER_FLOOD
  - NATURAL_DISASTER_FLOODING
  - NATURAL_DISASTER_FLOODS
  - NATURAL_DISASTER_FLOOD_WATER
  - TAX_FNCACT
  - TAX_FNCACT_EXECUTIVE
  - TAX_FNCACT_METEOROLOGIST
  - TAX_FNCACT_WRITER
  - TAX_WORLDMAMMALS
  - TAX_WORLDMAMMALS_SEAL
  - UNGP_FORESTS_RIVERS_OCEANS
  - URBAN
  - WB_1160_SHOCKS_AND_VULNERABILITY
  - WB_133_INFORMATION_AND_COMMUNICATION_TECHNOLOGIES
  - WB_137_WATER
  - WB_1458_HEALTH_PROMOTION_AND_DISEASE_PREVENTION
  - WB_1462_WATER_SANITATION_AND_HYGIENE
  - WB_621_HEALTH_NUTRITION_AND_POPULATION
  - WB_635_PUBLIC_HEALTH
  - WB_652_ICT_APPLICATIONS
  - WB_658_ENTERPRISE_APPLICATIONS
  - WB_662_SOCIAL_MEDIA
  - WB_678_DIGITAL_GOVERNMENT
  - WB_694_BROADCAST_AND_MEDIA
  - WB_695_POVERTY

========================================================================================================================
[3] Score: 12

URL:
https://www.kcrg.com/2025/03/15/threat-tornadoes-moves-us-south-after-big-storm-unleashes-winds-fans-wildfires/

Signals:
  Theme Match      : True
  URL Match        : True
  Weather Org      : True
  Grid Org         : False
  US Location      : True

Themes:
  -
  - AFFECT
  - BORDER
  - CRISISLEX_C03_WELLBEING_HEALTH
  - CRISISLEX_C04_LOGISTICS_TRANSPORT
  - CRISISLEX_C07_SAFETY
  - CRISISLEX_CRISISLEXREC
  - CRISISLEX_O01_WEATHER
  - CRISISLEX_O02_RESPONSEAGENCIESATCRISIS
  - CRISISLEX_T01_CAUTION_ADVICE
  - CRISISLEX_T02_INJURED
  - CRISISLEX_T03_DEAD
  - CRISISLEX_T09_DISPLACEDRELOCATEDEVACUATED
  - CRISISLEX_T11_UPDATESSYMPATHY
  - EDUCATION
  - ENV_CLIMATECHANGE
  - EPU_CATS_MIGRATION_FEAR_FEAR
  - EPU_POLICY
  - EPU_POLICY_AUTHORITIES
  - KILL
  - MANMADE_DISASTER
  - MANMADE_DISASTER_IMPLIED
  - MANMADE_DISASTER_KNOCKED_OUT_POWER
  - NATURAL_DISASTER
  - NATURAL_DISASTER_BLIZZARD
  - NATURAL_DISASTER_DUST_STORM
  - NATURAL_DISASTER_EXTREME_WEATHER
  - NATURAL_DISASTER_HIGH_WINDS
  - NATURAL_DISASTER_HURRICANE
  - NATURAL_DISASTER_SEVERE_WEATHER
  - NATURAL_DISASTER_STORM_SYSTEM
  - NATURAL_DISASTER_STRONG_WINDS
  - NATURAL_DISASTER_TORNADO
  - NATURAL_DISASTER_TORNADOES
  - NATURAL_DISASTER_TWISTERS
  - NATURAL_DISASTER_VIOLENT_TORNADOES
  - NATURAL_DISASTER_WHITEOUT
  - NATURAL_DISASTER_WILDFIRE
  - NATURAL_DISASTER_WILDFIRES
  - POWER_OUTAGE
  - SOC_POINTSOFINTEREST
  - SOC_POINTSOFINTEREST_SCHOOLS
  - SOC_POINTSOFINTEREST_UNIVERSITY
  - TAX_DISEASE
  - TAX_DISEASE_OUTBREAK
  - TAX_ETHNICITY
  - TAX_ETHNICITY_CANADIAN
  - TAX_FNCACT
  - TAX_FNCACT_AUTHORITIES
  - TAX_FNCACT_BUTLER
  - TAX_FNCACT_CORONER
  - TAX_FNCACT_DRIVER
  - TAX_FNCACT_MAN
  - TAX_FNCACT_OFFICIALS
  - TAX_FNCACT_TRUCK_DRIVER
  - TAX_FNCACT_WALKER
  - TAX_FNCACT_WOMAN
  - TAX_WORLDLANGUAGES
  - TAX_WORLDLANGUAGES_ALABAMA
  - UNGP_CLIMATE_CHANGE_ACTION
  - UNGP_FORESTS_RIVERS_OCEANS
  - UNREST_BELLIGERENT
  - WB_1777_FORESTS
  - WB_2165_HEALTH_EMERGENCIES
  - WB_2166_HEALTH_EMERGENCY_PREPAREDNESS_AND_DISASTER_RESPONSE
  - WB_2167_PANDEMICS
  - WB_566_ENVIRONMENT_AND_NATURAL_RESOURCES
  - WB_590_ECOSYSTEMS
  - WB_621_HEALTH_NUTRITION_AND_POPULATION
  - WB_635_PUBLIC_HEALTH
  - WOUND

========================================================================================================================
[4] Score: 10

URL:
https://www.myklgr.com/syndicated-article/?id=1619744

Signals:
  Theme Match      : False
  URL Match        : False
  Weather Org      : False
  Grid Org         : True
  US Location      : True

Themes:
  -
  - EDUCATION
  - SOC_POINTSOFINTEREST
  - SOC_POINTSOFINTEREST_HIGH_SCHOOL
  - SOC_POINTSOFINTEREST_SCHOOL
  - SOC_POINTSOFINTEREST_UNIVERSITY
  - TAX_FNCACT
  - TAX_FNCACT_ENGINEERS
  - TAX_FNCACT_STUDENTS

========================================================================================================================
[5] Score: 9

URL:
https://www.wjhg.com/2025/05/30/hurricane-season-2025-starts-june-1st-heres-what-you-need-know/

Signals:
  Theme Match      : True
  URL Match        : True
  Weather Org      : False
  Grid Org         : False
  US Location      : True

Themes:
  -
  - CRISISLEX_CRISISLEXREC
  - CRISISLEX_O01_WEATHER
  - MEDIA_SOCIAL
  - NATURAL_DISASTER
  - NATURAL_DISASTER_HURRICANE
  - NATURAL_DISASTER_HURRICANES
  - TAX_FNCACT
  - TAX_FNCACT_OFFICIALS
  - TAX_FNCACT_SPECIALIST
  - UNGP_FORESTS_RIVERS_OCEANS
  - WB_137_WATER

========================================================================================================================
[6] Score: 9

URL:
https://www.kwch.com/2025/04/29/storm-chances-remain-it-will-be-hitmiss/

Signals:
  Theme Match      : True
  URL Match        : True
  Weather Org      : False
  Grid Org         : False
  US Location      : True

Themes:
  -
  - CRISISLEX_O01_WEATHER
  - NATURAL_DISASTER
  - NATURAL_DISASTER_HIGH_WINDS
  - NATURAL_DISASTER_SEVERE_WEATHER
  - TAX_WORLDLANGUAGES
  - TAX_WORLDLANGUAGES_KANSAS
  - UNREST_BELLIGERENT

========================================================================================================================
[7] Score: 8

URL:
https://www.fox35orlando.com/news/tropical-outlook-eyes-florida-possibility-mid-august-climate-prediction-center

Signals:
  Theme Match      : True
  URL Match        : False
  Weather Org      : True
  Grid Org         : False
  US Location      : True

Themes:
  -
  - CRISISLEX_CRISISLEXREC
  - CRISISLEX_O01_WEATHER
  - EPU_POLICY
  - EPU_POLICY_GOVERNMENT
  - GENERAL_GOVERNMENT
  - MARITIME
  - NATURAL_DISASTER
  - NATURAL_DISASTER_HURRICANE
  - NATURAL_DISASTER_TROPICAL_STORM
  - TAX_FNCACT
  - TAX_FNCACT_METEOROLOGIST
  - TAX_WORLDMAMMALS
  - TAX_WORLDMAMMALS_FOX
  - UNGP_FORESTS_RIVERS_OCEANS
  - WB_137_WATER
  - WB_1774_CLIMATE_FORECASTING
  - WB_567_CLIMATE_CHANGE
  - WB_571_CLIMATE_SCIENCE

========================================================================================================================
[8] Score: 5

URL:
https://www.wsws.org/en/articles/2025/11/01/jxjt-n01.html

Signals:
  Theme Match      : True
  URL Match        : False
  Weather Org      : False
  Grid Org         : False
  US Location      : True

Themes:
  -
  - ARMEDCONFLICT
  - CRISISLEX_C07_SAFETY
  - CRISISLEX_CRISISLEXREC
  - CRISISLEX_O02_RESPONSEAGENCIESATCRISIS
  - CRISISLEX_T01_CAUTION_ADVICE
  - DEMOCRACY
  - ENV_FISHERY
  - EPU_CATS_MIGRATION_FEAR_FEAR
  - EPU_CATS_NATIONAL_SECURITY
  - EPU_ECONOMY
  - EPU_ECONOMY_HISTORIC
  - EPU_POLICY
  - EPU_POLICY_GOVERNMENT
  - EPU_POLICY_POLICY
  - FREESPEECH
  - GENERAL_GOVERNMENT
  - LEADER
  - MANMADE_DISASTER_IMPLIED
  - MARITIME
  - MARITIME_INCIDENT
  - MARITIME_PIRACY
  - MEDIA_MSM
  - MILITARY
  - NATURAL_DISASTER
  - NATURAL_DISASTER_EARTHQUAKE
  - ORGANIZED_CRIME
  - PUBLIC_TRANSPORT
  - SCIENCE
  - SECURITY_SERVICES
  - SELF_IDENTIFIED_HUMAN_RIGHTS
  - SLFID_MILITARY_BUILDUP
  - SOC_GENERALCRIME
  - SOC_POINTSOFINTEREST
  - SOC_POINTSOFINTEREST_HEADQUARTERS
  - SOC_USSECURITYAGENCIES
  - SURVEILLANCE
  - TAX_DISEASE
  - TAX_DISEASE_EMERGENCIES
  - TAX_ETHNICITY
  - TAX_ETHNICITY_AUSTRALIAN
  - TAX_ETHNICITY_CHINESE
  - TAX_ETHNICITY_FRENCH
  - TAX_ETHNICITY_RAPA_NUI
  - TAX_FNCACT
  - TAX_FNCACT_AGENTS
  - TAX_FNCACT_AMBASSADOR
  - TAX_FNCACT_CHIEF
  - TAX_FNCACT_CHIEFS
  - TAX_FNCACT_COOK
  - TAX_FNCACT_MINISTER
  - TAX_FNCACT_MINISTERS
  - TAX_FNCACT_NAVY
  - TAX_FNCACT_OFFICIAL
  - TAX_FNCACT_POLICE
  - TAX_FNCACT_REPRESENTATIVES
  - TAX_FNCACT_SECRETARY
  - TAX_FNCACT_SECRETARY_GENERAL
  - TAX_POLITICAL_PARTY
  - TAX_POLITICAL_PARTY_LABOR_PARTY
  - TAX_WORLDLANGUAGES
  - TAX_WORLDLANGUAGES_CHINESE
  - TAX_WORLDLANGUAGES_COOK_ISLANDS
  - TAX_WORLDLANGUAGES_EASTER_ISLAND
  - TAX_WORLDLANGUAGES_FRENCH
  - TAX_WORLDLANGUAGES_RAPA_NUI
  - TAX_WORLDLANGUAGES_TUVALU
  - UNGP_FORESTS_RIVERS_OCEANS
  - UNGP_POLITICAL_FREEDOMS
  - UNREST_BELLIGERENT
  - USPEC_POLICY1
  - USPEC_POLITICS_GENERAL1
  - WB_1024_PUBLIC_INTERNATIONAL_LAW
  - WB_1026_TREATIES
  - WB_133_INFORMATION_AND_COMMUNICATION_TECHNOLOGIES
  - WB_2375_ICT_METHODS_AND_PROCEDURES
  - WB_2432_FRAGILITY_CONFLICT_AND_VIOLENCE
  - WB_2433_CONFLICT_AND_VIOLENCE
  - WB_2453_ORGANIZED_CRIME
  - WB_2470_PEACE_OPERATIONS_AND_CONFLICT_MANAGEMENT
  - WB_2490_NATIONAL_PROTECTION_AND_SECURITY
  - WB_653_ENTERPRISE_ARCHITECTURE
  - WB_657_INTEROPERABILITY
  - WB_678_DIGITAL_GOVERNMENT
  - WB_694_BROADCAST_AND_MEDIA
  - WB_696_PUBLIC_SECTOR_MANAGEMENT
  - WB_845_LEGAL_AND_REGULATORY_FRAMEWORK
  - WB_962_INTERNATIONAL_LAW

========================================================================================================================
[9] Score: 5

URL:
https://deltadiscovery.com/murkowski-speaks-out-on-rescission-package/

Signals:
  Theme Match      : True
  URL Match        : False
  Weather Org      : False
  Grid Org         : False
  US Location      : True

Themes:
  -
  - CONSTITUTIONAL
  - CRISISLEX_CRISISLEXREC
  - CRISISLEX_T01_CAUTION_ADVICE
  - CRISISLEX_T11_UPDATESSYMPATHY
  - DELAY
  - ECON_BUDGET_DEFICIT
  - ECON_INFLATION
  - EDUCATION
  - EPU_CATS_FISCAL_POLICY
  - EPU_CATS_MIGRATION_FEAR_FEAR
  - EPU_POLICY
  - EPU_POLICY_AUTHORITIES
  - EPU_POLICY_BUDGET
  - EPU_POLICY_CONGRESS
  - EPU_POLICY_LAW
  - EPU_POLICY_REFORM
  - EPU_POLICY_SPENDING
  - GENERAL_GOVERNMENT
  - GENERAL_HEALTH
  - GOV_LOCALGOV
  - HEALTH_PANDEMIC
  - LEADER
  - LEGISLATION
  - LITERACY
  - MANMADE_DISASTER_IMPLIED
  - MEDIA_MSM
  - MEDICAL
  - NATURAL_DISASTER
  - NATURAL_DISASTER_EARTHQUAKE
  - NATURAL_DISASTER_NATURAL_DISASTERS
  - NATURAL_DISASTER_TSUNAMI
  - PROTEST
  - RELIGION
  - SCIENCE
  - SHORTAGE
  - SOC_INNOVATION
  - SOC_POINTSOFINTEREST
  - SOC_POINTSOFINTEREST_SCHOOL
  - SOC_POINTSOFINTEREST_SCHOOLS
  - TAX_FNCACT
  - TAX_FNCACT_AUTHORITIES
  - TAX_FNCACT_BOARD_MEMBERS
  - TAX_FNCACT_CHAMPIONS
  - TAX_FNCACT_CHILD
  - TAX_FNCACT_CHILDREN
  - TAX_FNCACT_DIRECTOR
  - TAX_FNCACT_DIRECTORS
  - TAX_FNCACT_EDUCATORS
  - TAX_FNCACT_EXECUTIVE
  - TAX_FNCACT_EXECUTIVE_DIRECTOR
  - TAX_FNCACT_GOVERNOR
  - TAX_FNCACT_GUIDE
  - TAX_FNCACT_JUDGE
  - TAX_FNCACT_LEADERS
  - TAX_FNCACT_PRESIDENT
  - TAX_FNCACT_SENATOR
  - TAX_FNCACT_STEWARDS
  - TAX_FNCACT_STUDENT
  - TAX_FNCACT_STUDENTS
  - TAX_FNCACT_TEACHER
  - TAX_FNCACT_WOMEN
  - TRANSPARENCY
  - UNGP_EDUCATION
  - UNGP_FORESTS_RIVERS_OCEANS
  - UNGP_HEALTHCARE
  - USPEC_POLICY1
  - USPEC_POLITICS_GENERAL1
  - USPEC_UNCERTAINTY1
  - VETO
  - WB_133_INFORMATION_AND_COMMUNICATION_TECHNOLOGIES
  - WB_134_SOCIAL_DEVELOPMENT
  - WB_135_TRANSPORT
  - WB_1467_EDUCATION_FOR_ALL
  - WB_1468_SOCIAL_DEMAND_FOR_EDUCATION
  - WB_1497_EDUCATION_MANAGEMENT_AND_ADMINISTRATION
  - WB_1502_EDUCATIONAL_DECENTRALIZATION
  - WB_164_MODES_OF_TRANSPORT
  - WB_165_AIR_TRANSPORT
  - WB_2126_RELIGIOUS_EDUCATION
  - WB_2141_EDUCATION_DISTRICTS
  - WB_2165_HEALTH_EMERGENCIES
  - WB_2166_HEALTH_EMERGENCY_PREPAREDNESS_AND_DISASTER_RESPONSE
  - WB_2167_PANDEMICS
  - WB_470_EDUCATION
  - WB_621_HEALTH_NUTRITION_AND_POPULATION
  - WB_635_PUBLIC_HEALTH
  - WB_678_DIGITAL_GOVERNMENT
  - WB_694_BROADCAST_AND_MEDIA
  - WB_696_PUBLIC_SECTOR_MANAGEMENT
  - WB_733_SOCIAL_ACCOUNTABILITY
  - WB_737_LOCAL_GOVERNANCE
  - WB_831_GOVERNANCE

========================================================================================================================
[10] Score: 5

URL:
https://www.yahoo.com/news/wynton-marsalis-twyla-tharp-groundhog-221708076.html

Signals:
  Theme Match      : True
  URL Match        : False
  Weather Org      : False
  Grid Org         : False
  US Location      : True

Themes:
  -
  - CRISISLEX_C06_WATER_SANITATION
  - CRISISLEX_CRISISLEXREC
  - CRISISLEX_T01_CAUTION_ADVICE
  - EDUCATION
  - EPU_ECONOMY_HISTORIC
  - MANMADE_DISASTER_IMPLIED
  - MEDIA_CENSORSHIP
  - MEDIA_MSM
  - MOVEMENT_GENERAL
  - NATURAL_DISASTER
  - NATURAL_DISASTER_FLOODING
  - SELF_IDENTIFIED_HUMAN_RIGHTS
  - SOC_INNOVATION
  - SOC_POINTSOFINTEREST
  - SOC_POINTSOFINTEREST_SCHOOL
  - SOC_POINTSOFINTEREST_UNIVERSITY
  - TAX_ETHNICITY
  - TAX_ETHNICITY_AMERICAN
  - TAX_ETHNICITY_AMERICANS
  - TAX_ETHNICITY_BLACK
  - TAX_FNCACT
  - TAX_FNCACT_ARTIST
  - TAX_FNCACT_ARTISTS
  - TAX_FNCACT_CHOREOGRAPHER
  - TAX_FNCACT_COMPOSER
  - TAX_FNCACT_DIRECTOR
  - TAX_FNCACT_PHOTOGRAPHER
  - TAX_FNCACT_REPORTER
  - TAX_FNCACT_SAXOPHONIST
  - TAX_FNCACT_WEATHERMAN
  - TAX_RELIGION
  - TAX_RELIGION_AFRICAN_DIASPORA
  - TAX_WORLDLANGUAGES
  - TAX_WORLDLANGUAGES_ARBOR
  - UNGP_POLITICAL_FREEDOMS
  - WB_133_INFORMATION_AND_COMMUNICATION_TECHNOLOGIES
  - WB_1699_METAL_ORE_MINING
  - WB_2937_SILVER
  - WB_507_ENERGY_AND_EXTRACTIVES
  - WB_678_DIGITAL_GOVERNMENT
  - WB_694_BROADCAST_AND_MEDIA
  - WB_895_MINING_SYSTEMS

========================================================================================================================
[11] Score: 5

URL:
https://www.news4jax.com/news/local/2025/03/31/jimmy-patronis-talks-legacy-as-floridas-cfo-future-goals-if-elected-to-house-seat/

Signals:
  Theme Match      : True
  URL Match        : False
  Weather Org      : False
  Grid Org         : False
  US Location      : True

Themes:
  -
  - CRISISLEX_CRISISLEXREC
  - CRISISLEX_O01_WEATHER
  - CRISISLEX_T11_UPDATESSYMPATHY
  - ECON_BUDGET_DEFICIT
  - ECON_INFLATION
  - ECON_WORLDCURRENCIES
  - ECON_WORLDCURRENCIES_DOLLARS
  - EPU_ECONOMY
  - EPU_ECONOMY_HISTORIC
  - EPU_POLICY
  - EPU_POLICY_GOVERNMENT
  - EPU_POLICY_SPENDING
  - GENERAL_GOVERNMENT
  - GENERAL_HEALTH
  - KILL
  - LEADER
  - MEDICAL
  - NATURAL_DISASTER
  - NATURAL_DISASTER_HURRICANES
  - SLFID_ECONOMIC_DEVELOPMENT
  - TAX_DISEASE
  - TAX_DISEASE_CANCER
  - TAX_FNCACT
  - TAX_FNCACT_CFO
  - TAX_FNCACT_CHIEF
  - TAX_FNCACT_CHIEF_FINANCIAL_OFFICER
  - TAX_FNCACT_CITIZENS
  - TAX_FNCACT_OFFICER
  - TAX_FNCACT_PRESIDENT
  - TAX_FNCACT_PUBLIC_SERVANTS
  - TAX_FNCACT_REPRESENTATIVES
  - TAX_FNCACT_SERVANTS
  - TAX_FNCACT_WOMEN
  - TAX_MILITARY_TITLE
  - TAX_MILITARY_TITLE_OFFICER
  - TRANSPARENCY
  - UNGP_FORESTS_RIVERS_OCEANS
  - USPEC_POLICY1
  - USPEC_POLITICS_GENERAL1
  - WB_1104_MACROECONOMIC_VULNERABILITY_AND_DEBT
  - WB_137_WATER
  - WB_1406_DISEASES
  - WB_1427_NON_COMMUNICABLE_DISEASE_AND_INJURY
  - WB_1431_CANCER
  - WB_1967_AGRICULTURAL_RISK_AND_SECURITY
  - WB_1973_FINANCIAL_RISK_REDUCTION
  - WB_337_INSURANCE
  - WB_435_AGRICULTURE_AND_FOOD_SECURITY
  - WB_442_INFLATION
  - WB_621_HEALTH_NUTRITION_AND_POPULATION

========================================================================================================================
[12] Score: 5

URL:
https://www.aol.co.uk/trump-officials-contacted-el-salvador-233708708.html

Signals:
  Theme Match      : True
  URL Match        : False
  Weather Org      : False
  Grid Org         : False
  US Location      : True

Themes:
  -
  - AFFECT
  - CRISISLEX_C07_SAFETY
  - EPU_CATS_MIGRATION_FEAR_MIGRATION
  - EPU_CATS_NATIONAL_SECURITY
  - EPU_POLICY
  - EPU_POLICY_POLICY
  - EPU_UNCERTAINTY
  - IMMIGRATION
  - LEADER
  - NATURAL_DISASTER
  - NATURAL_DISASTER_ICE
  - SOC_POINTSOFINTEREST
  - SOC_POINTSOFINTEREST_PRISON
  - SOC_USSECURITYAGENCIES
  - TAX_FNCACT
  - TAX_FNCACT_ADVISERS
  - TAX_FNCACT_EXECUTIVE
  - TAX_FNCACT_JUDGE
  - TAX_FNCACT_LAWYERS
  - TAX_FNCACT_MAN
  - TAX_FNCACT_OFFICIAL
  - TAX_FNCACT_OFFICIALS
  - TAX_FNCACT_PRESIDENT
  - TAX_FNCACT_SECRETARY
  - TAX_FNCACT_SECRETARY_OF_STATE
  - TERROR
  - TRIAL
  - UNGP_FORESTS_RIVERS_OCEANS
  - UNREST_BELLIGERENT
  - USPEC_POLICY1
  - USPEC_POLITICS_GENERAL1
  - WB_1014_CRIMINAL_JUSTICE
  - WB_1281_MANUFACTURING
  - WB_1921_PRIVATE_SECTOR_DEVELOPMENT
  - WB_2432_FRAGILITY_CONFLICT_AND_VIOLENCE
  - WB_2433_CONFLICT_AND_VIOLENCE
  - WB_2462_POLITICAL_VIOLENCE_AND_WAR
  - WB_2467_TERRORISM
  - WB_2470_PEACE_OPERATIONS_AND_CONFLICT_MANAGEMENT
  - WB_2490_NATIONAL_PROTECTION_AND_SECURITY
  - WB_2495_DETENTION_PRISON_AND_CORRECTIONS_REFORM
  - WB_2670_JOBS
  - WB_2769_JOBS_STRATEGIES
  - WB_2836_MIGRATION_POLICIES_AND_JOBS
  - WB_2837_IMMIGRATION
  - WB_346_COMPETITIVE_INDUSTRIES
  - WB_696_PUBLIC_SECTOR_MANAGEMENT
  - WB_818_INDUSTRY_POLICY_AND_REAL_SECTORS
  - WB_840_JUSTICE

========================================================================================================================
[13] Score: 5

URL:
https://www.dailyitem.com/cnhi_network/trumps-mass-deportation-plans-face-myriad-challenges/article_a6634977-0408-5f59-a536-9390613b893d.html

Signals:
  Theme Match      : True
  URL Match        : False
  Weather Org      : False
  Grid Org         : False
  US Location      : True

Themes:
  -
  - AFFECT
  - AGRICULTURE
  - ALLIANCE
  - ARREST
  - BAN
  - BORDER
  - CRISISLEX_C07_SAFETY
  - CRISISLEX_CRISISLEXREC
  - CRISISLEX_T11_UPDATESSYMPATHY
  - DRUG_TRADE
  - ELECTION
  - EPU_CATS_MIGRATION_FEAR_FEAR
  - EPU_CATS_MIGRATION_FEAR_MIGRATION
  - EPU_ECONOMY
  - EPU_ECONOMY_HISTORIC
  - EPU_POLICY
  - EPU_POLICY_AUTHORITIES
  - EPU_POLICY_CONGRESS
  - EPU_POLICY_GOVERNMENT
  - EPU_POLICY_LAW
  - EPU_POLICY_POLICY
  - EPU_POLICY_POLITICAL
  - GENERAL_GOVERNMENT
  - IMMIGRATION
  - LEADER
  - LEGISLATION
  - MANMADE_DISASTER_IMPLIED
  - MILITARY_COOPERATION
  - NATURAL_DISASTER
  - NATURAL_DISASTER_ICE
  - REFUGEES
  - RELIGION
  - SECURITY_SERVICES
  - SHORTAGE
  - SLFID_CIVIL_LIBERTIES
  - SOC_GENERALCRIME

In [65]:

from datetime import datetime, timedelta

def timestamps_for_day(date: str, files_per_day: int = 96) -> list[str]:
    """
    GDELT GKG v2 files are available every 15 minutes.
    """
    start = datetime.strptime(date, "%Y-%m-%d")

    return [
        (start + timedelta(minutes=15 * i)).strftime("%Y%m%d%H%M%S")
        for i in range(files_per_day)
    ]

In [66]:
date= '2025-01-01'


timestamps = timestamps_for_day(date)

In [67]:
for i in timestamps:
    print(i)

20250101000000
20250101001500
20250101003000
20250101004500
20250101010000
20250101011500
20250101013000
20250101014500
20250101020000
20250101021500
20250101023000
20250101024500
20250101030000
20250101031500
20250101033000
20250101034500
20250101040000
20250101041500
20250101043000
20250101044500
20250101050000
20250101051500
20250101053000
20250101054500
20250101060000
20250101061500
20250101063000
20250101064500
20250101070000
20250101071500
20250101073000
20250101074500
20250101080000
20250101081500
20250101083000
20250101084500
20250101090000
20250101091500
20250101093000
20250101094500
20250101100000
20250101101500
20250101103000
20250101104500
20250101110000
20250101111500
20250101113000
20250101114500
20250101120000
20250101121500
20250101123000
20250101124500
20250101130000
20250101131500
20250101133000
20250101134500
20250101140000
20250101141500
20250101143000
20250101144500
20250101150000
20250101151500
20250101153000
20250101154500
20250101160000
20250101161500
20250101163000
20250101164500
20250101170000
20250101171500
20250101173000
20250101174500
20250101180000
20250101181500
20250101183000
20250101184500
20250101190000
20250101191500
20250101193000
20250101194500
20250101200000
20250101201500
20250101203000
20250101204500
20250101210000
20250101211500
20250101213000
20250101214500
20250101220000
20250101221500
20250101223000
20250101224500
20250101230000
20250101231500
20250101233000
20250101234500

In [68]:
start = '2025-01-01'
end = '2025-01-04'


delta = pd.date_range(pd.to_datetime(start), pd.to_datetime(end))

In [69]:
delta

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04'], dtype='datetime64[ns]', freq='D')

In [70]:
records = df.to_dict(orient='records')

In [71]:
print(len(records))

171090

In [73]:
print(records[0])

{'GKGRECORDID': '20250101000000-0', 'DATE': '20250101000000', 'SourceCollectionIdentifier': '1', 'SourceCommonName': 'crooksandliars.com', 'DocumentIdentifier': 'https://crooksandliars.com/2024/12/retired-general-warns-musk-national', 'Counts': None, 'V2Counts': None, 'Themes': 'CRISISLEX_C07_SAFETY;WB_2470_PEACE_OPERATIONS_AND_CONFLICT_MANAGEMENT;WB_2432_FRAGILITY_CONFLICT_AND_VIOLENCE;WB_2490_NATIONAL_PROTECTION_AND_SECURITY;EPU_CATS_NATIONAL_SECURITY;MILITARY;TAX_MILITARY_TITLE;TAX_MILITARY_TITLE_LIEUTENANT;TAX_FNCACT;TAX_FNCACT_LIEUTENANT;TAX_MILITARY_TITLE_LIEUTENANT_GENERAL;TAX_FNCACT_LIEUTENANT_GENERAL;TAX_ETHNICITY;TAX_ETHNICITY_CHINESE;TAX_WORLDLANGUAGES;TAX_WORLDLANGUAGES_CHINESE;TAX_FNCACT_COMMUNIST;USPEC_POLITICS_GENERAL1;TAX_POLITICAL_PARTY;TAX_POLITICAL_PARTY_COMMUNIST_PARTY;EPU_ECONOMY_HISTORIC;MANMADE_DISASTER_IMPLIED;TAX_FNCACT_LEADERS;GENERAL_GOVERNMENT;EPU_POLICY;EPU_POLICY_GOVERNMENT;LEGISLATION;TAX_FNCACT_CHIEF;', 'V2Themes': 'TAX_MILITARY_TITLE_LIEUTENANT,90;TAX_MILITARY_TITLE_LIEUTENANT,1366;TAX_FNCACT_LIEUTENANT,90;TAX_FNCACT_LIEUTENANT,1366;USPEC_POLITICS_GENERAL1,203;USPEC_POLITICS_GENERAL1,248;USPEC_POLITICS_GENERAL1,947;MANMADE_DISASTER_IMPLIED,283;TAX_POLITICAL_PARTY_COMMUNIST_PARTY,203;TAX_POLITICAL_PARTY_COMMUNIST_PARTY,947;CRISISLEX_C07_SAFETY,46;CRISISLEX_C07_SAFETY,1316;TAX_MILITARY_TITLE_LIEUTENANT_GENERAL,98;TAX_MILITARY_TITLE_LIEUTENANT_GENERAL,1374;TAX_FNCACT_LIEUTENANT_GENERAL,98;TAX_FNCACT_LIEUTENANT_GENERAL,1374;MILITARY,71;MILITARY,1355;TAX_ETHNICITY_CHINESE,187;TAX_ETHNICITY_CHINESE,669;TAX_WORLDLANGUAGES_CHINESE,187;TAX_WORLDLANGUAGES_CHINESE,669;TAX_FNCACT_LEADERS,510;LEGISLATION,912;EPU_ECONOMY_HISTORIC,227;EPU_ECONOMY_HISTORIC,1003;EPU_ECONOMY_HISTORIC,1097;EPU_ECONOMY_HISTORIC,1214;TAX_FNCACT_COMMUNIST,197;TAX_FNCACT_COMMUNIST,941;GENERAL_GOVERNMENT,680;EPU_POLICY_GOVERNMENT,680;WB_2470_PEACE_OPERATIONS_AND_CONFLICT_MANAGEMENT,46;WB_2470_PEACE_OPERATIONS_AND_CONFLICT_MANAGEMENT,1316;WB_2432_FRAGILITY_CONFLICT_AND_VIOLENCE,46;WB_2432_FRAGILITY_CONFLICT_AND_VIOLENCE,1316;WB_2490_NATIONAL_PROTECTION_AND_SECURITY,46;WB_2490_NATIONAL_PROTECTION_AND_SECURITY,1316;EPU_CATS_NATIONAL_SECURITY,46;EPU_CATS_NATIONAL_SECURITY,1316;TAX_FNCACT_CHIEF,1479;', 'Locations': '4#Shanghai, Shanghai, China#CH#CH23#31.2222#121.458#-1924465;2#New York, United States#US#USNY#42.1497#-74.9384#NY;1#China#CH#CH#35#105#CH', 'V2Locations': '4#Shanghai, Shanghai, China#CH#CH23#13243#31.2222#121.458#-1924465#720;1#Chinese#CH#CH##35#105#CH#187;1#Chinese#CH#CH##35#105#CH#669;1#China#CH#CH##35#105#CH#727;1#China#CH#CH##35#105#CH#840;1#China#CH#CH##35#105#CH#1012;1#China#CH#CH##35#105#CH#1115;1#China#CH#CH##35#105#CH#1494;2#New York, United States#US#USNY##42.1497#-74.9384#NY#360;2#New York, United States#US#USNY##42.1497#-74.9384#NY#1436', 'Persons': 'elon musk', 'V2Persons': 'Elon Musk,9;Elon Musk,1283', 'Organizations': 'spacex;new york times;chinese communist party;u s army', 'V2Organizations': 'Spacex,417;Spacex,1473;New York Times,366;New York Times,1442;Chinese Communist Party,203', 'Tone': '-0.387596899224806,3.87596899224806,4.26356589147287,8.13953488372093,17.4418604651163,0,234', 'Dates': None, 'GCAM': 'wc:234,c12.1:16,c12.10:23,c12.11:1,c12.12:4,c12.13:3,c12.14:16,c12.2:1,c12.3:6,c12.5:9,c12.6:1,c12.7:10,c12.8:3,c12.9:18,c14.1:11,c14.10:11,c14.11:25,c14.2:11,c14.3:16,c14.4:1,c14.5:24,c14.6:1,c14.7:1,c14.9:4,c15.102:1,c15.103:1,c15.112:2,c15.143:1,c15.148:1,c15.175:1,c15.233:2,c15.57:2,c15.71:1,c15.86:2,c16.100:8,c16.101:5,c16.102:1,c16.105:1,c16.106:5,c16.109:7,c16.11:9,c16.110:43,c16.111:1,c16.114:6,c16.115:4,c16.116:3,c16.117:9,c16.118:8,c16.12:13,c16.120:8,c16.121:28,c16.124:1,c16.125:21,c16.126:10,c16.127:16,c16.128:1,c16.129:25,c16.13:1,c16.130:1,c16.131:11,c16.134:17,c16.135:2,c16.138:4,c16.139:5,c16.14:1,c16.140:5,c16.141:1,c16.142:1,c16.143:1,c16.145:21,c16.146:16,c16.151:1,c16.153:3,c16.155:1,c16.156:1,c16.157:6,c16.158:1,c16.159:14,c16.161:19,c16.162:7,c16.163:13,c16.164:4,c16.165:1,c16.18:1,c16.19:4,c16.2:25,c16.20:1,c16.21:2,c16.22:2,c16.23:3,c16.26:22,c16.28:4,c16.29:1,c16.3:5,c16.31:11,c16.32:4,c16.33:9,c16.34:1,c16.35:11,c16.37:20,c16.38:5,c16.4:17,c16.41:8,c16.42:2,c16.45:5,c16.47:43,c16.49:2,c16.5:1,c16.50:1,c16.52:16,c16.56:7,c16.57:124,c16.58:12,c16.6:14,c16.60:4,c16.61:4,c16.62:5,c16.63:4,c16.64:1,c16.65:5,c16.66:2,c16.68:15,c16.69:5,c16.7:16,c16.70:14,c16.72:2,c16.73:2,c16.74:2,c16.75:6,c16.77:4,c16.78:11,c16.79:1,c16.81:3,c16.82:2,c16.84:15,c16.85:3,c16.87:25,c16.88:17,c16.89:3,c16.90:12,c16.91:5,c16.92:8,c16.94:15,c16.95:27,c16.96:5,c16.98:10,c17.1:65,c17.10:32,c17.11:31,c17.12:5,c17.13:4,c17.14:1,c17.15:22,c17.16:8,c17.19:25,c17.2:6,c17.20:2,c17.22:5,c17.23:1,c17.24:24,c17.25:5,c17.26:1,c17.27:22,c17.28:6,c17.29:7,c17.30:3,c17.31:7,c17.32:4,c17.33:10,c17.34:4,c17.35:5,c17.36:4,c17.37:2,c17.39:5,c17.4:52,c17.40:2,c17.41:8,c17.42:18,c17.43:9,c17.5:47,c17.6:1,c17.7:26,c17.8:26,c17.9:4,c18.180:2,c18.193:10,c18.195:2,c18.21:1,c18.342:4,c18.35:2,c18.72:2,c18.73:4,c2.1:10,c2.100:1,c2.101:2,c2.102:9,c2.103:8,c2.104:37,c2.106:7,c2.107:1,c2.108:1,c2.109:5,c2.11:8,c2.110:9,c2.113:2,c2.114:6,c2.115:2,c2.116:5,c2.119:67,c2.12:7,c2.120:3,c2.121:8,c2.122:5,c2.125:12,c2.126:7,c2.127:24,c2.128:10,c2.129:35,c2.130:1,c2.132:10,c2.133:3,c2.134:1,c2.135:1,c2.137:2,c2.138:2,c2.139:2,c2.14:15,c2.140:1,c2.141:6,c2.142:4,c2.143:30,c2.144:7,c2.145:2,c2.146:5,c2.147:38,c2.148:14,c2.15:12,c2.150:1,c2.151:1,c2.153:5,c2.154:15,c2.155:24,c2.156:18,c2.157:23,c2.158:13,c2.160:11,c2.162:2,c2.166:2,c2.167:4,c2.168:1,c2.169:7,c2.17:1,c2.170:8,c2.171:1,c2.172:4,c2.173:2,c2.176:1,c2.177:17,c2.179:5,c2.18:5,c2.180:5,c2.181:10,c2.182:1,c2.183:10,c2.185:48,c2.186:2,c2.187:10,c2.188:1,c2.189:1,c2.19:2,c2.190:1,c2.191:5,c2.192:1,c2.193:16,c2.195:30,c2.196:5,c2.197:2,c2.198:14,c2.199:2,c2.200:3,c2.203:10,c2.204:13,c2.205:1,c2.206:2,c2.207:6,c2.208:2,c2.209:3,c2.21:3,c2.210:18,c2.213:4,c2.214:13,c2.215:1,c2.217:1,c2.22:2,c2.220:2,c2.221:8,c2.222:2,c2.223:10,c2.225:4,c2.226:4,c2.227:1,c2.23:19,c2.25:10,c2.26:13,c2.27:13,c2.28:3,c2.30:11,c2.31:7,c2.32:1,c2.34:8,c2.35:2,c2.36:1,c2.37:2,c2.39:39,c2.4:3,c2.40:1,c2.44:15,c2.45:27,c2.46:17,c2.47:1,c2.48:8,c2.5:2,c2.50:4,c2.52:15,c2.54:17,c2.55:1,c2.56:1,c2.57:2,c2.58:13,c2.6:5,c2.60:1,c2.62:8,c2.64:9,c2.65:4,c2.66:2,c2.70:1,c2.71:1,c2.73:5,c2.75:29,c2.76:154,c2.77:31,c2.78:28,c2.79:2,c2.80:34,c2.81:3,c2.82:7,c2.83:1,c2.84:1,c2.86:7,c2.87:1,c2.88:1,c2.89:10,c2.9:3,c2.90:1,c2.93:6,c2.95:39,c2.97:3,c2.98:7,c2.99:5,c25.1:2,c25.5:4,c25.6:1,c25.7:1,c3.1:11,c3.2:15,c35.1:6,c35.11:2,c35.14:3,c35.15:3,c35.2:1,c35.20:10,c35.25:1,c35.31:13,c35.32:6,c35.33:11,c35.4:2,c35.5:2,c39.12:3,c39.14:2,c39.19:3,c39.2:6,c39.28:1,c39.3:11,c39.37:8,c39.39:4,c39.4:7,c39.40:2,c39.41:3,c39.5:2,c4.16:3,c4.17:2,c4.20:1,c4.23:5,c40.5:9,c41.1:8,c42.1:79,c5.10:19,c5.11:2,c5.12:32,c5.16:2,c5.17:2,c5.18:1,c5.19:2,c5.21:3,c5.22:3,c5.23:2,c5.24:5,c5.26:4,c5.27:1,c5.28:3,c5.29:4,c5.3:1,c5.30:19,c5.31:2,c5.33:4,c5.34:6,c5.35:14,c5.36:19,c5.37:1,c5.4:7,c5.40:21,c5.42:3,c5.43:3,c5.44:1,c5.46:36,c5.47:5,c5.49:16,c5.50:16,c5.51:12,c5.52:19,c5.53:20,c5.54:7,c5.56:5,c5.59:1,c5.6:8,c5.60:6,c5.61:13,c5.62:92,c5.7:10,c5.8:16,c5.9:10,c6.1:4,c6.3:1,c6.4:4,c6.5:4,c6.6:4,c7.1:9,c7.2:14,c8.10:2,c8.17:1,c8.2:2,c8.23:3,c8.25:7,c8.29:1,c8.3:2,c8.31:6,c8.37:7,c8.38:10,c8.39:6,c8.4:5,c8.40:3,c8.41:2,c8.42:7,c8.43:8,c8.8:1,c9.1:5,c9.10:3,c9.1003:1,c9.1005:1,c9.1006:1,c9.101:1,c9.1011:1,c9.102:1,c9.103:1,c9.1035:1,c9.107:3,c9.108:1,c9.109:2,c9.11:1,c9.111:1,c9.113:1,c9.122:6,c9.124:1,c9.128:10,c9.129:3,c9.130:5,c9.135:2,c9.141:3,c9.142:2,c9.155:2,c9.158:12,c9.160:1,c9.161:1,c9.162:5,c9.164:1,c9.165:2,c9.168:1,c9.169:1,c9.170:1,c9.173:1,c9.175:2,c9.177:4,c9.178:1,c9.184:7,c9.188:2,c9.19:2,c9.190:1,c9.193:1,c9.195:1,c9.196:1,c9.198:5,c9.200:1,c9.201:1,c9.202:1,c9.205:2,c9.206:1,c9.208:1,c9.209:1,c9.210:1,c9.211:1,c9.212:1,c9.230:1,c9.233:1,c9.235:1,c9.244:1,c9.246:2,c9.247:1,c9.248:1,c9.249:1,c9.250:1,c9.255:1,c9.262:1,c9.27:2,c9.270:1,c9.282:1,c9.284:1,c9.288:3,c9.293:1,c9.3:5,c9.32:2,c9.33:2,c9.334:1,c9.34:5,c9.35:1,c9.358:1,c9.36:1,c9.360:1,c9.381:1,c9.382:2,c9.383:6,c9.384:5,c9.387:1,c9.39:2,c9.391:1,c9.394:1,c9.396:5,c9.40:1,c9.405:1,c9.415:6,c9.430:3,c9.44:3,c9.447:1,c9.458:3,c9.459:1,c9.461:1,c9.463:2,c9.466:1,c9.468:1,c9.473:4,c9.476:1,c9.479:5,c9.48:2,c9.480:2,c9.485:1,c9.489:3,c9.491:1,c9.498:6,c9.511:4,c9.513:4,c9.514:2,c9.515:1,c9.517:1,c9.519:2,c9.521:1,c9.522:2,c9.528:1,c9.533:1,c9.537:2,c9.539:1,c9.54:1,c9.540:2,c9.542:1,c9.546:1,c9.551:2,c9.556:2,c9.557:2,c9.56:2,c9.560:3,c9.561:2,c9.562:1,c9.564:1,c9.566:1,c9.568:1,c9.570:2,c9.575:3,c9.576:3,c9.579:5,c9.582:5,c9.6:1,c9.60:1,c9.61:4,c9.615:1,c9.619:3,c9.624:2,c9.631:2,c9.633:1,c9.636:2,c9.640:3,c9.641:2,c9.642:7,c9.648:6,c9.649:2,c9.650:5,c9.653:10,c9.654:1,c9.655:1,c9.658:2,c9.659:4,c9.66:4,c9.660:4,c9.663:1,c9.664:2,c9.665:2,c9.667:2,c9.668:4,c9.669:2,c9.670:1,c9.671:1,c9.672:6,c9.676:1,c9.678:1,c9.679:1,c9.682:1,c9.683:1,c9.686:1,c9.687:3,c9.690:1,c9.692:2,c9.693:3,c9.696:1,c9.698:1,c9.70:1,c9.701:6,c9.704:10,c9.708:8,c9.71:1,c9.710:4,c9.718:1,c9.719:1,c9.720:7,c9.721:1,c9.722:1,c9.723:1,c9.724:3,c9.726:12,c9.727:1,c9.73:1,c9.730:5,c9.733:1,c9.734:1,c9.735:3,c9.736:4,c9.737:3,c9.739:2,c9.740:7,c9.741:2,c9.744:1,c9.747:1,c9.748:8,c9.754:4,c9.757:2,c9.758:1,c9.759:1,c9.76:7,c9.760:1,c9.761:4,c9.762:5,c9.765:1,c9.766:6,c9.767:12,c9.769:1,c9.77:3,c9.770:1,c9.771:1,c9.772:3,c9.774:1,c9.775:8,c9.776:2,c9.778:2,c9.789:2,c9.79:1,c9.790:1,c9.793:1,c9.795:1,c9.8:3,c9.800:1,c9.801:1,c9.802:2,c9.804:1,c9.810:2,c9.812:8,c9.813:1,c9.815:2,c9.816:3,c9.817:1,c9.819:2,c9.82:3,c9.820:1,c9.826:6,c9.828:2,c9.83:10,c9.831:3,c9.833:2,c9.834:4,c9.837:1,c9.839:2,c9.843:1,c9.846:2,c9.849:1,c9.851:3,c9.855:1,c9.859:1,c9.86:1,c9.860:6,c9.864:5,c9.865:2,c9.866:1,c9.867:2,c9.868:5,c9.87:2,c9.874:1,c9.877:4,c9.88:1,c9.882:1,c9.89:1,c9.896:2,c9.899:1,c9.9:2,c9.90:1,c9.900:1,c9.904:1,c9.906:1,c9.911:6,c9.915:4,c9.916:1,c9.92:1,c9.923:2,c9.924:1,c9.926:2,c9.93:1,c9.930:5,c9.935:8,c9.939:1,c9.945:1,c9.949:2,c9.95:1,c9.952:2,c9.953:1,c9.954:1,c9.955:2,c9.96:4,c9.962:6,c9.964:5,c9.966:6,c9.969:4,c9.972:9,c9.978:5,c9.98:1,c9.980:7,c9.981:1,c9.984:2,c9.985:2,c9.986:4,c9.988:2,c9.989:1,c9.99:1,v10.1:0.24732545045045,v10.2:0.27390350877193,v11.1:0.0473257983193277,v19.1:6.24035714285714,v19.2:5.33035714285714,v19.3:5.47142857142857,v19.4:6.2325,v19.5:5.26964285714286,v19.6:5.56285714285714,v19.7:6.23392857142857,v19.8:5.43321428571428,v19.9:5.32178571428572,v20.1:0.656,v20.10:-0.75,v20.11:0.574818181818182,v20.12:-0.625,v20.13:0.4485,v20.14:-0.4584,v20.15:0.414275862068966,v20.16:-0.423666666666667,v20.3:0.656,v20.4:-0.75,v20.5:0.7655,v20.6:-0.75,v20.7:0.760333333333333,v20.8:-0.75,v20.9:0.623875,v21.1:5.39928205128206,v26.1:0.969565217391304,v42.10:0.0282364860632911,v42.11:0.0157222026962025,v42.2:0.0973645227974684,v42.3:0.106918112911392,v42.4:0.0968038948987342,v42.5:0.103677384708861,v42.6:0.0802409570253165,v42.7:-0.0432703997721519,v42.8:0.00975186825316455,v42.9:0.0373922487468354', 'SharingImage': 'https://crooksandliars.com/files/embeds/2024/12/63683.jpg', 'RelatedImages': None, 'SocialImageEmbeds': None, 'SocialVideoEmbeds': 'https://youtube.com/embed/3q5NHISy1G0;', 'Quotations': None, 'AllNames': 'Elon Musk,10;Lieutenant General Russel,108;Chinese Communist Party,217;New York Times,390;Communist Party,1003;President-elect Donald Trump,1342;New York Times,1527', 'Amounts': None, 'TranslationInfo': None, 'Extras': '<PAGE_LINKS>https://www.independent.co.uk/news/world/americas/us-politics/elon-musk-nationl-security-risk-nyt-op-ed-b2671611.html;https://www.nytimes.com/2024/12/29/opinion/elon-musk-china-classified-secrets-national-security-russia-doge.html</PAGE_LINKS><PAGE_AUTHORS>Susie Madrak</PAGE_AUTHORS><PAGE_PRECISEPUBTIMESTAMP>20241231205600</PAGE_PRECISEPUBTIMESTAMP><PAGE_ALTURL_AMP>https://crooksandliars.com/2024/12/retired-general-warns-musk-national/amp</PAGE_ALTURL_AMP><PAGE_TITLE>Retired General Warns That Musk Is A National Security Risk</PAGE_TITLE>', 'GDELT_TIMESTAMP': '20250101000000', 'GDELT_URL': 'http://data.gdeltproject.org/gdeltv2/20250101000000.gkg.csv.zip', 'DATETIME': Timestamp('2025-01-01 00:00:00')}